#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = ti/runtime/argsmain
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/utils.js:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/utils.js
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/xdc.tci:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/xdc.tci
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/template.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/template.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/om2.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/om2.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/xmlgen.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/xmlgen.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/xmlgen2.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/xmlgen2.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/Warnings.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/Warnings.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/IPackage.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/IPackage.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/package.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/package.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/services/global/Clock.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/services/global/Clock.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/services/global/Trace.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/services/global/Trace.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/bld.js:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/bld.js
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/BuildEnvironment.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/PackageContents.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/PackageContents.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/_gen.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/_gen.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/Library.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/Library.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/Executable.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/Executable.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/Repository.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/Repository.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/Configuration.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/Configuration.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/Script.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/Script.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/Manifest.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/Manifest.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/Utils.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/Utils.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/ITarget.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/ITarget.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/ITarget2.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/ITarget2.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/ITarget3.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/ITarget3.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/ITargetFilter.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/ITargetFilter.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/package.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/package.xs
package.mak: config.bld
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/ITarget.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/ITarget.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/C28_large.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/C28_large.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/C28_float.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/C28_float.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/package.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/package.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/elf/ITarget.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/elf/ITarget.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/elf/package.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/elf/package.xs
package.mak: package.bld
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/work/am57xx_evm-linux-gnueabi/openmp-rtos/2_05_00_00-r0.tisdk0/git/src/ti/runtime/ompbios/package.bld:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/work/am57xx_evm-linux-gnueabi/openmp-rtos/2_05_00_00-r0.tisdk0/git/src/ti/runtime/ompbios/package.bld
endif

ti.targets.elf.C66.rootDir ?= /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/x86_64-linux/usr/share/ti/cgt-c6x
ti.targets.elf.packageBase ?= /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/elf/
.PRECIOUS: $(XDCCFGDIR)/%.oe66
.PHONY: all,e66 .dlls,e66 .executables,e66 test,e66
all,e66: .executables,e66
.executables,e66: .libraries,e66
.executables,e66: .dlls,e66
.dlls,e66: .libraries,e66
.libraries,e66: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,e66
	@$(ECHO) xdc .executables,e66
	@$(ECHO) xdc .libraries,e66
	@$(ECHO) xdc .dlls,e66


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_ti.runtime.argsmain.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package ti.runtime.argsmain" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

ifeq (,$(MK_NOGENDEPS))
-include package/package.cfg.dep
endif

package/package.cfg.xdc.inc: .interfaces $(XDCROOT)/packages/xdc/cfg/cfginc.js package.xdc
	@$(MSG) generating schema include file list ...
	$(CONFIG) -f $(XDCROOT)/packages/xdc/cfg/cfginc.js ti.runtime.argsmain $@

.libraries,e66 .libraries: lib/ti_runtime_argsmain_debug_e66.ae66

-include lib/ti_runtime_argsmain_debug_e66.ae66.mak
lib/ti_runtime_argsmain_debug_e66.ae66: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/ti_runtime_argsmain_debug_e66/package/package_ti.runtime.argsmain.oe66 package/lib/lib/ti_runtime_argsmain_debug_e66/./args_main_rtsc.oe66  into $@ ...
	$(ti.targets.elf.C66.rootDir)/bin/ar6x  rq $@   package/lib/lib/ti_runtime_argsmain_debug_e66/package/package_ti.runtime.argsmain.oe66 package/lib/lib/ti_runtime_argsmain_debug_e66/./args_main_rtsc.oe66 
lib/ti_runtime_argsmain_debug_e66.ae66: export C_DIR=
lib/ti_runtime_argsmain_debug_e66.ae66: PATH:=$(ti.targets.elf.C66.rootDir)/bin/:$(PATH)

clean,e66 clean::
	-$(RM) lib/ti_runtime_argsmain_debug_e66.ae66
.libraries,e66 .libraries: lib/ti_runtime_argsmain_release_e66.ae66

-include lib/ti_runtime_argsmain_release_e66.ae66.mak
lib/ti_runtime_argsmain_release_e66.ae66: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/ti_runtime_argsmain_release_e66/package/package_ti.runtime.argsmain.oe66 package/lib/lib/ti_runtime_argsmain_release_e66/./args_main_rtsc.oe66  into $@ ...
	$(ti.targets.elf.C66.rootDir)/bin/ar6x  rq $@   package/lib/lib/ti_runtime_argsmain_release_e66/package/package_ti.runtime.argsmain.oe66 package/lib/lib/ti_runtime_argsmain_release_e66/./args_main_rtsc.oe66 
lib/ti_runtime_argsmain_release_e66.ae66: export C_DIR=
lib/ti_runtime_argsmain_release_e66.ae66: PATH:=$(ti.targets.elf.C66.rootDir)/bin/:$(PATH)

clean,e66 clean::
	-$(RM) lib/ti_runtime_argsmain_release_e66.ae66
test:;
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
.PHONY: package_ti.runtime.argsmain.oe66,copy
package_ti.runtime.argsmain.oe66,copy : package_ti.runtime.argsmain.oe66,0,copy package_ti.runtime.argsmain.oe66,1,copy 
	@

package_ti.runtime.argsmain.oe66,0,copy : package/lib/lib/ti_runtime_argsmain_debug_e66/package/package_ti.runtime.argsmain.oe66
package_ti.runtime.argsmain.oe66,1,copy : package/lib/lib/ti_runtime_argsmain_release_e66/package/package_ti.runtime.argsmain.oe66
.PHONY: package_ti.runtime.argsmain.se66,copy
package_ti.runtime.argsmain.se66,copy : package_ti.runtime.argsmain.se66,0,copy package_ti.runtime.argsmain.se66,1,copy 
	@

package_ti.runtime.argsmain.se66,0,copy : package/lib/lib/ti_runtime_argsmain_debug_e66/package/package_ti.runtime.argsmain.se66
package_ti.runtime.argsmain.se66,1,copy : package/lib/lib/ti_runtime_argsmain_release_e66/package/package_ti.runtime.argsmain.se66
.PHONY: args_main_rtsc.oe66,copy
args_main_rtsc.oe66,copy : args_main_rtsc.oe66,0,copy args_main_rtsc.oe66,1,copy 
	@

args_main_rtsc.oe66,0,copy : package/lib/lib/ti_runtime_argsmain_debug_e66/./args_main_rtsc.oe66
args_main_rtsc.oe66,1,copy : package/lib/lib/ti_runtime_argsmain_release_e66/./args_main_rtsc.oe66
.PHONY: args_main_rtsc.se66,copy
args_main_rtsc.se66,copy : args_main_rtsc.se66,0,copy args_main_rtsc.se66,1,copy 
	@

args_main_rtsc.se66,0,copy : package/lib/lib/ti_runtime_argsmain_debug_e66/./args_main_rtsc.se66
args_main_rtsc.se66,1,copy : package/lib/lib/ti_runtime_argsmain_release_e66/./args_main_rtsc.se66

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg $(XDCROOT)/packages/xdc/cfg/Main.xs | .interfaces
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,ti_runtime_argsmain_src
ifeq (,$(MK_NOGENDEPS))
-include package/rel/ti_runtime_argsmain_src.tar.gz.dep
endif
package/rel/ti_runtime_argsmain_src/ti/runtime/argsmain/package/package.rel.xml: package/package.bld.xml
package/rel/ti_runtime_argsmain_src/ti/runtime/argsmain/package/package.rel.xml: package/build.cfg
package/rel/ti_runtime_argsmain_src/ti/runtime/argsmain/package/package.rel.xml: config.bld
package/rel/ti_runtime_argsmain_src/ti/runtime/argsmain/package/package.rel.xml: package.bld
package/rel/ti_runtime_argsmain_src/ti/runtime/argsmain/package/package.rel.xml: goals.xs
package/rel/ti_runtime_argsmain_src/ti/runtime/argsmain/package/package.rel.xml: ./args_main_rtsc.c
package/rel/ti_runtime_argsmain_src/ti/runtime/argsmain/package/package.rel.xml: package/package.xdc.inc
package/rel/ti_runtime_argsmain_src/ti/runtime/argsmain/package/package.rel.xml: package/package.cfg.xdc.inc
package/rel/ti_runtime_argsmain_src/ti/runtime/argsmain/package/package.rel.xml: .force
	@$(MSG) generating external release references $@ ...
	$(XS) $(JSENV) -f $(XDCROOT)/packages/xdc/bld/rel.js $(MK_RELOPTS) . $@

ti_runtime_argsmain_src.tar.gz: package/rel/ti_runtime_argsmain_src.xdc.inc package/rel/ti_runtime_argsmain_src/ti/runtime/argsmain/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/ti_runtime_argsmain_src.xdc.inc,package/rel/ti_runtime_argsmain_src.tar.gz.dep)


release release,ti_runtime_argsmain_src: all ti_runtime_argsmain_src.tar.gz
clean:: .clean
	-$(RM) ti_runtime_argsmain_src.tar.gz
	-$(RM) package/rel/ti_runtime_argsmain_src.xdc.inc
	-$(RM) package/rel/ti_runtime_argsmain_src.tar.gz.dep


.PHONY: release,ti_runtime_argsmain_all
ifeq (,$(MK_NOGENDEPS))
-include package/rel/ti_runtime_argsmain_all.tar.gz.dep
endif
package/rel/ti_runtime_argsmain_all/ti/runtime/argsmain/package/package.rel.xml: package/package.bld.xml
package/rel/ti_runtime_argsmain_all/ti/runtime/argsmain/package/package.rel.xml: package/build.cfg
package/rel/ti_runtime_argsmain_all/ti/runtime/argsmain/package/package.rel.xml: package/package.xdc.inc
package/rel/ti_runtime_argsmain_all/ti/runtime/argsmain/package/package.rel.xml: package/package.cfg.xdc.inc
package/rel/ti_runtime_argsmain_all/ti/runtime/argsmain/package/package.rel.xml: lib/ti_runtime_argsmain_debug_e66.ae66
package/rel/ti_runtime_argsmain_all/ti/runtime/argsmain/package/package.rel.xml: lib/ti_runtime_argsmain_release_e66.ae66
package/rel/ti_runtime_argsmain_all/ti/runtime/argsmain/package/package.rel.xml: .force
	@$(MSG) generating external release references $@ ...
	$(XS) $(JSENV) -f $(XDCROOT)/packages/xdc/bld/rel.js $(MK_RELOPTS) . $@

ti_runtime_argsmain_all.tar.gz: package/rel/ti_runtime_argsmain_all.xdc.inc package/rel/ti_runtime_argsmain_all/ti/runtime/argsmain/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/ti_runtime_argsmain_all.xdc.inc,package/rel/ti_runtime_argsmain_all.tar.gz.dep)


release release,ti_runtime_argsmain_all: all ti_runtime_argsmain_all.tar.gz
clean:: .clean
	-$(RM) ti_runtime_argsmain_all.tar.gz
	-$(RM) package/rel/ti_runtime_argsmain_all.xdc.inc
	-$(RM) package/rel/ti_runtime_argsmain_all.tar.gz.dep

clean:: .clean
	-$(RM) .libraries $(wildcard .libraries,*)
clean:: 
	-$(RM) .dlls $(wildcard .dlls,*)
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard lib))
    $(shell $(MKDIR) lib)
endif
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
ifeq (,$(wildcard package/lib/lib))
    $(shell $(MKDIR) package/lib/lib)
endif
ifeq (,$(wildcard package/lib/lib/ti_runtime_argsmain_debug_e66))
    $(shell $(MKDIR) package/lib/lib/ti_runtime_argsmain_debug_e66)
endif
ifeq (,$(wildcard package/lib/lib/ti_runtime_argsmain_debug_e66/package))
    $(shell $(MKDIR) package/lib/lib/ti_runtime_argsmain_debug_e66/package)
endif
ifeq (,$(wildcard package/lib/lib/ti_runtime_argsmain_release_e66))
    $(shell $(MKDIR) package/lib/lib/ti_runtime_argsmain_release_e66)
endif
ifeq (,$(wildcard package/lib/lib/ti_runtime_argsmain_release_e66/package))
    $(shell $(MKDIR) package/lib/lib/ti_runtime_argsmain_release_e66/package)
endif
endif
clean::
	-$(RMDIR) package


