/*
 *  Copyright 2016 by Texas Instruments Incorporated.
 *
 */

/* this file was generated by xdc/bld/stddefs.xdt */
/*
 *  @(#) ti.targets.arm.elf; 1, 0, 0,0; 8-18-2016 15:55:53; /db/ztree/library/trees/xdctargets/xdctargets-l06/src/ xlibrary

 */

