#!/bin/sh
if type update-rc.d >/dev/null 2>/dev/null; then
	if [ -n "$D" ]; then
		OPT="-r $D"
	else
		OPT="-s"
	fi
	update-rc.d $OPT run-postinsts start 99 S .
fi
OPTS=""

if [ -n "$D" ]; then
    OPTS="--root=$D"
fi

if type systemctl >/dev/null 2>/dev/null; then
	systemctl $OPTS enable run-postinsts.service

	if [ -z "$D" -a "enable" = "enable" ]; then
		systemctl restart run-postinsts.service
	fi
fi
