######################################################################
# Automatically generated by qmake (2.01a) Fri Oct 21 08:15:16 2011
######################################################################

TEMPLATE = app
TARGET = matrix_browser
DEPENDPATH += .
INCLUDEPATH += .
QT       +=   webkit webkitwidgets
# Input
SOURCES += main.cpp MatrixWebView.cpp
HEADERS = MatrixWebView.h

# install
target.path = .
INSTALLS += target
