#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

include Makedocs.mk
include makefile
unexport MAKEFILE_LIST
override PKGDIR = ti/imglib
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/Manifest.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/Manifest.xs
package.mak: docs/bundle/doxygen/doxyfile.xdt
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/services/io/package.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/services/io/package.xs
C:/builds/IMGLIB/TI_PRODUCT_3_1_1_0/imglib/ti/mas/swtools/Version2.h.xdt:
package.mak: C:/builds/IMGLIB/TI_PRODUCT_3_1_1_0/imglib/ti/mas/swtools/Version2.h.xdt
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/_gen.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/_gen.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/template.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/template.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/om2.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/om2.xs
C:/builds/IMGLIB/TI_PRODUCT_3_1_1_0/imglib/ti/mas/swtools/Version2.xdt:
package.mak: C:/builds/IMGLIB/TI_PRODUCT_3_1_1_0/imglib/ti/mas/swtools/Version2.xdt
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/xmlgen2.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/xmlgen2.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/ti/targets/elf/TMS470.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/ti/targets/elf/TMS470.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/services/global/Clock.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/services/global/Clock.xs
package.mak: docs/bundle/manifest/doxyfile.xdt
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/xmlgen.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/xmlgen.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/ti/targets/ITarget.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/ti/targets/ITarget.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/ti/targets/elf/package.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/ti/targets/elf/package.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/ti/targets/elf/ITarget.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/ti/targets/elf/ITarget.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/ti/targets/package.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/ti/targets/package.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/include/utils.tci:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/include/utils.tci
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/Utils.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/Utils.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/xdc.tci:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/xdc.tci
C:/builds/IMGLIB/TI_PRODUCT_3_1_1_0/imglib/ti/mas/swtools/Copy.xs:
package.mak: C:/builds/IMGLIB/TI_PRODUCT_3_1_1_0/imglib/ti/mas/swtools/Copy.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/PackageContents.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/PackageContents.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/Executable.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/Executable.xs
C:/builds/IMGLIB/TI_PRODUCT_3_1_1_0/imglib/ti/mas/swtools/CommonBld.xs:
package.mak: C:/builds/IMGLIB/TI_PRODUCT_3_1_1_0/imglib/ti/mas/swtools/CommonBld.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/Library.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/Library.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/ITarget.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/ITarget.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/services/global/Trace.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/services/global/Trace.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/package.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/package.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/Script.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/Script.xs
package.mak: docs/manifest/manifest.xml.xdt
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/BuildEnvironment.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/BuildEnvironment.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/services/io/File.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/services/io/File.xs
C:/builds/IMGLIB/TI_PRODUCT_3_1_1_0/imglib/ti/mas/swtools/config.bld:
package.mak: C:/builds/IMGLIB/TI_PRODUCT_3_1_1_0/imglib/ti/mas/swtools/config.bld
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/Repository.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/Repository.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/bld.js:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/bld.js
package.mak: docs/doxygen/doxyfile.xdt
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/IPackage.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/IPackage.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/package.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/package.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/ITargetFilter.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/ITargetFilter.xs
package.mak: package.bld
endif

all,54 .libraries,54 .dlls,54 .executables,54 test,54:;
all,54f .libraries,54f .dlls,54f .executables,54f test,54f:;
all,55 .libraries,55 .dlls,55 .executables,55 test,55:;
all,55L .libraries,55L .dlls,55L .executables,55L test,55L:;
all,674 .libraries,674 .dlls,674 .executables,674 test,674:;
all,674e .libraries,674e .dlls,674e .executables,674e test,674e:;
all,e674 .libraries,e674 .dlls,e674 .executables,e674 test,e674:;
all,e674e .libraries,e674e .dlls,e674e .executables,e674e test,e674e:;
all,66 .libraries,66 .dlls,66 .executables,66 test,66:;
all,e66 .libraries,e66 .dlls,e66 .executables,e66 test,e66:;
all,66e .libraries,66e .dlls,66e .executables,66e test,66e:;
all,e66e .libraries,e66e .dlls,e66e .executables,e66e test,e66e:;
all,64 .libraries,64 .dlls,64 .executables,64 test,64:;
all,64e .libraries,64e .dlls,64e .executables,64e test,64e:;
all,64P .libraries,64P .dlls,64P .executables,64P test,64P:;
all,64Pe .libraries,64Pe .dlls,64Pe .executables,64Pe test,64Pe:;
all,e64P .libraries,e64P .dlls,e64P .executables,e64P test,e64P:;
all,e64Pe .libraries,e64Pe .dlls,e64Pe .executables,e64Pe test,e64Pe:;

all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_ti.imglib.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package ti.imglib" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

ifneq (clean,$(MAKECMDGOALS))
-include package/package.cfg.dep
endif

package/package.ext.xml: package/package.cfg.xdc.inc
package/package.cfg.xdc.inc: $(XDCROOT)/packages/xdc/cfg/cfginc.js package.xdc
	@$(MSG) generating schema include file list ...
	$(CONFIG) -f $(XDCROOT)/packages/xdc/cfg/cfginc.js ti.imglib $@

test:;
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,ti_imglib_src_c66x_3_1_1_0
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_gen_iq//c66/IMG_corr_gen_iq.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_le16_8//c66/IMG_yc_demux_le16_8.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i16_c16/IMG_corr_3x3_i16_c16.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_be16_16//c66/IMG_yc_demux_be16_16.sa
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_median_3x3_16//c66/IMG_median_3x3_16.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2max_16/IMG_thr_gt2max_16.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_median_3x3_16s//c66//IMG_median_3x3_16s_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: imglib_3_1_1_0_release_notes.html
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_median_3x3_16//c66//IMG_median_3x3_16_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_dilate_bin//c66//IMG_dilate_bin_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_le16_8/IMG_yc_demux_le16_8_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_le16_16/IMG_yc_demux_le16_16_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sad_8x8/IMG_sad_8x8_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sad_8x8/IMG_sad_8x8_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_11x11_i16s_c16s//c66//IMG_corr_11x11_i16s_c16s_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_5x5_i8_c16s/IMG_conv_5x5_i8_c16s_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_mad_16x16//c66//IMG_mad_16x16_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2max_16//c66//IMG_thr_gt2max_16_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i8_c16s//c66//IMG_corr_3x3_i8_c16s_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_ycbcr422pl_to_rgb565//c66/IMG_ycbcr422pl_to_rgb565.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_5x5_i8_c16s/IMG_conv_5x5_i8_c16s_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i16_c16//c66/IMG_corr_3x3_i16_c16.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2thr_8/IMG_thr_gt2thr_8_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2thr_8/IMG_thr_gt2thr_8.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_ycbcr422pl_to_rgb565//c66/IMG_ycbcr422pl_to_rgb565.h
ti_imglib_src_c66x_3_1_1_0.zip: package/package.rel.dot
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_quantize/IMG_quantize_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_perimeter_16//c66/IMG_perimeter_16.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_quantize/IMG_quantize_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_ycbcr422pl_to_rgb565/IMG_ycbcr422pl_to_rgb565_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_perimeter_16//c66/IMG_perimeter_16.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_boundary_8//c66/IMG_boundary_8.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2min_16/IMG_thr_le2min_16_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_boundary_8//c66/IMG_boundary_8.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2min_16/IMG_thr_le2min_16_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_le16_8//c66//IMG_yc_demux_le16_8_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_5x5_i8_c16s//c66/IMG_conv_5x5_i8_c16s.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_5x5_i8_c16s//c66/IMG_conv_5x5_i8_c16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_be16_16/IMG_yc_demux_be16_16_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_mad_16x16//c66/IMG_mad_16x16.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_7x7_i8_c8s/IMG_conv_7x7_i8_c8s_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_ycbcr422pl_to_rgb565/IMG_ycbcr422pl_to_rgb565_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_boundary_16s/IMG_boundary_16s_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_wave_horz/IMG_wave_horz_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_pix_expand//c66//IMG_pix_expand_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_ycbcr422pl_to_rgb565/IMG_ycbcr422pl_to_rgb565_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_wave_horz/IMG_wave_horz_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_mad_16x16//c66/IMG_mad_16x16.s
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_3x3_16s/IMG_sobel_3x3_16s_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_5x5_i8_c16s/IMG_conv_5x5_i8_c16s_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_11x11_i16s_c16s/IMG_corr_11x11_i16s_c16s_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2thr_8//c66//IMG_thr_le2thr_8_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_boundary_8/IMG_boundary_8_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_pix_expand/IMG_pix_expand_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_boundary_8//c66//IMG_boundary_8_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_mad_8x8//c66//IMG_mad_8x8_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2max_8//c66/IMG_thr_gt2max_8.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_5x5_i8_c16s//c66//IMG_conv_5x5_i8_c16s_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2max_8//c66/IMG_thr_gt2max_8.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_histogram_8/IMG_histogram_8.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_idct_8x8_12q4//c66/IMG_idct_8x8_12q4.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i8_c8/IMG_corr_3x3_i8_c8_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_median_3x3_16/IMG_median_3x3_16_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_7x7_16s//c66/IMG_sobel_7x7_16s.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_3x3_i8_c8s/IMG_conv_3x3_i8_c8s_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_idct_8x8_12q4//c66/IMG_idct_8x8_12q4.s
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_7x7_16s//c66/IMG_sobel_7x7_16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_7x7_i8_c16s//c66//IMG_conv_7x7_i8_c16s_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_3x3_i8_c8s/IMG_conv_3x3_i8_c8s_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_3x3_16s/IMG_sobel_3x3_16s_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_histogram_8//c66//IMG_histogram_8_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_be16_8//c66//IMG_yc_demux_be16_8_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_pix_sat/IMG_pix_sat.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sad_16x16//c66/IMG_sad_16x16.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_median_3x3_16/IMG_median_3x3_16.h
ti_imglib_src_c66x_3_1_1_0.zip: docs/manifest/Software_Manifest.html
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sad_16x16//c66/IMG_sad_16x16.s
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_11x11_i8_c16s/IMG_corr_11x11_i8_c16s_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2thr_16//c66//IMG_thr_le2thr_16_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_histogram_16/IMG_histogram_16_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_3x3_16//c66//IMG_sobel_3x3_16_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_7x7_16s/IMG_sobel_7x7_16s_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_erode_bin/IMG_erode_bin.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_3x3_16s//c66//IMG_sobel_3x3_16s_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_5x5_i8_c8s/IMG_conv_5x5_i8_c8s_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_perimeter_16//c66//IMG_perimeter_16_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_3x3_16//c66//IMG_sobel_3x3_16_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_11x11_i8_c8s/IMG_conv_11x11_i8_c8s_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_wave_horz//c66//IMG_wave_horz_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_11x11_i8_c8s/IMG_conv_11x11_i8_c8s_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2thr_16/IMG_thr_le2thr_16_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_fdct_8x8/IMG_fdct_8x8_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2thr_16/IMG_thr_le2thr_16_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_le16_8/IMG_yc_demux_le16_8_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_errdif_bin_16//c66//IMG_errdif_bin_16_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_mad_16x16/IMG_mad_16x16_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2thr_16//c66//IMG_thr_gt2thr_16_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_3x3_16//c66/IMG_sobel_3x3_16.sa
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2max_8/IMG_thr_gt2max_8_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_3x3_i16_c16s//c66/IMG_conv_3x3_i16_c16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2max_8/IMG_thr_gt2max_8_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2max_8/IMG_thr_gt2max_8_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_5x5_i16s_c16s/IMG_corr_5x5_i16s_c16s_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_be16_8/IMG_yc_demux_be16_8_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_fdct_8x8//c66//IMG_fdct_8x8_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_11x11_i16s_c16s//c66//IMG_corr_11x11_i16s_c16s_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_dilate_bin//c66//IMG_dilate_bin_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_5x5_i16s_c16s/IMG_corr_5x5_i16s_c16s_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_be16_8/IMG_yc_demux_be16_8_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_le16_16/IMG_yc_demux_le16_16_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_errdif_bin_16/IMG_errdif_bin_16_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_7x7_16s/IMG_sobel_7x7_16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_erode_bin/IMG_erode_bin_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_median_3x3_8//c66//IMG_median_3x3_8_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_mad_16x16/IMG_mad_16x16_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_errdif_bin_16/IMG_errdif_bin_16_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_3x3_i16_c16s//c66//IMG_conv_3x3_i16_c16s_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_mad_16x16/IMG_mad_16x16_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2thr_8/IMG_thr_le2thr_8_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_perimeter_8/IMG_perimeter_8.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_median_3x3_16s/IMG_median_3x3_16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2thr_8/IMG_thr_le2thr_8_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_5x5_i8_c16s/IMG_conv_5x5_i8_c16s_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_median_3x3_8//c66//IMG_median_3x3_8_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_gen_i16s_c16s//c66//IMG_corr_gen_i16s_c16s_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_7x7_i8_c16s/IMG_conv_7x7_i8_c16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_5x5_i8_c8s//c66//IMG_conv_5x5_i8_c8s_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_median_3x3_8/IMG_median_3x3_8_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2max_8//c66//IMG_thr_gt2max_8_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_gen_i16s_c16s/IMG_corr_gen_i16s_c16s_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_median_3x3_8/IMG_median_3x3_8_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_gen_i16s_c16s/IMG_corr_gen_i16s_c16s_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_11x11_i16s_c16s//c66//IMG_conv_11x11_i16s_c16s_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_le16_16//c66/IMG_yc_demux_le16_16.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_perimeter_8//c66//IMG_perimeter_8_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_perimeter_16/IMG_perimeter_16_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_median_3x3_8/IMG_median_3x3_8.h
ti_imglib_src_c66x_3_1_1_0.zip: ./package/projects
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_wave_vert/IMG_wave_vert.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_3x3_i8_c8s/IMG_conv_3x3_i8_c8s_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_pix_sat/IMG_pix_sat_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_5x5_16s/IMG_sobel_5x5_16s.h
ti_imglib_src_c66x_3_1_1_0.zip: docs/relnotes_archive
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_7x7_i8_c16s//c66/IMG_conv_7x7_i8_c16s.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_7x7_i8_c16s//c66/IMG_conv_7x7_i8_c16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_errdif_bin_8/IMG_errdif_bin_8_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_perimeter_16//c66//IMG_perimeter_16_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_errdif_bin_8/IMG_errdif_bin_8_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_5x5_i16s_c16s/IMG_conv_5x5_i16s_c16s_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_le16_16//c66//IMG_yc_demux_le16_16_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2thr_8/IMG_thr_le2thr_8_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2min_16/IMG_thr_le2min_16.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_errdif_bin_8//c66//IMG_errdif_bin_8_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_3x3_8/IMG_sobel_3x3_8_d.c
ti_imglib_src_c66x_3_1_1_0.zip: docs/doxygen/doxyfile.xdt
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_11x11_i16s_c16s/IMG_conv_11x11_i16s_c16s_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_5x5_16s//c66/IMG_sobel_5x5_16s.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_7x7_i8_c16s/IMG_conv_7x7_i8_c16s_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_3x3_i16_c16s//c66//IMG_conv_3x3_i16_c16s_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_5x5_16s//c66/IMG_sobel_5x5_16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_7x7_i8_c16s/IMG_conv_7x7_i8_c16s_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: package/build.cfg
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_median_3x3_16s/IMG_median_3x3_16s_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_3x3_16s/IMG_sobel_3x3_16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_5x5_i8_c16s//c66//IMG_conv_5x5_i8_c16s_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_fdct_8x8/IMG_fdct_8x8_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_errdif_bin_16//c66/IMG_errdif_bin_16.sa
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_boundary_16s//c66/IMG_boundary_16s.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_mad_8x8//c66/IMG_mad_8x8.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_5x5_i16s_c16s/IMG_conv_5x5_i16s_c16s_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_boundary_16s//c66/IMG_boundary_16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_be16_16//c66//IMG_yc_demux_be16_16_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_mad_8x8//c66/IMG_mad_8x8.s
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_clipping_16s/IMG_clipping_16s_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2thr_8//c66//IMG_thr_gt2thr_8_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_ycbcr422pl_to_rgb565/IMG_ycbcr422pl_to_rgb565.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_perimeter_8/IMG_perimeter_8_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_histogram_8/IMG_histogram_8_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_7x7_i8_c8s/IMG_conv_7x7_i8_c8s_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_histogram_8/IMG_histogram_8_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_5x5_16s//c66//IMG_sobel_5x5_16s_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_errdif_bin_16//c66//IMG_errdif_bin_16_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_7x7_i8_c8s/IMG_conv_7x7_i8_c8s_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_7x7_i8_c8s/IMG_conv_7x7_i8_c8s_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_idct_8x8_12q4/IMG_idct_8x8_12q4_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i16s_c16s/IMG_corr_3x3_i16s_c16s_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_7x7_i16s_c16s/IMG_conv_7x7_i16s_c16s_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_errdif_bin_8//c66//IMG_errdif_bin_8_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_le16_8/IMG_yc_demux_le16_8.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_gen_i16s_c16s/IMG_corr_gen_i16s_c16s_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2min_16/IMG_thr_le2min_16_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i16s_c16s/IMG_corr_3x3_i16s_c16s_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i16s_c16s/IMG_corr_3x3_i16s_c16s_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_11x11_i8_c16s/IMG_corr_11x11_i8_c16s_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_be16_8//c66//IMG_yc_demux_be16_8_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2thr_16/IMG_thr_le2thr_16_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_11x11_i8_c16s/IMG_corr_11x11_i8_c16s_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_le16_8/IMG_yc_demux_le16_8_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_median_3x3_8//c66/IMG_median_3x3_8.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2thr_16/IMG_thr_gt2thr_16_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_le16_8/IMG_yc_demux_le16_8_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_median_3x3_8//c66/IMG_median_3x3_8.h
ti_imglib_src_c66x_3_1_1_0.zip: docs/bundle/doxygen/doxyfile.xdt
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2thr_16/IMG_thr_gt2thr_16_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_histogram_8//c66//IMG_histogram_8_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2thr_8/IMG_thr_le2thr_8.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_gen_iq/IMG_corr_gen_iq.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2min_8/IMG_thr_le2min_8_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i16_c16//c66/IMG_corr_3x3_i16_c16.sa
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i8_c8/IMG_corr_3x3_i8_c8_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2thr_8/IMG_thr_gt2thr_8_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sad_8x8/IMG_sad_8x8.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2thr_8/IMG_thr_gt2thr_8_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2thr_16//c66//IMG_thr_le2thr_16_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_gen_i16s_c16s/IMG_corr_gen_i16s_c16s_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_7x7_i8_c16s/IMG_conv_7x7_i8_c16s_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: docs/doxygen/IMGLIB_Function_Reference.chm
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_idct_8x8_12q4//c66//IMG_idct_8x8_12q4_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_perimeter_8//c66//IMG_perimeter_8_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_wave_horz//c66//IMG_wave_horz_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i16_c16/IMG_corr_3x3_i16_c16_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_7x7_i8_c16s/IMG_conv_7x7_i8_c16s_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2max_16/IMG_thr_gt2max_16_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2max_16/IMG_thr_gt2max_16_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i8_c8//c66/IMG_corr_3x3_i8_c8.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2thr_8/IMG_thr_gt2thr_8_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_be16_16//c66//IMG_yc_demux_be16_16_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2max_16/IMG_thr_gt2max_16_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i8_c8//c66/IMG_corr_3x3_i8_c8.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_gen_iq/IMG_corr_gen_iq_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_11x11_i8_c8s//c66//IMG_conv_11x11_i8_c8s_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_3x3_16/IMG_sobel_3x3_16_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2max_8/IMG_thr_gt2max_8_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_3x3_i16_c16s/IMG_conv_3x3_i16_c16s_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_3x3_i16s_c16s/IMG_conv_3x3_i16s_c16s_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_3x3_16/IMG_sobel_3x3_16_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_boundary_8/IMG_boundary_8_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_3x3_16/IMG_sobel_3x3_16_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_3x3_8/IMG_sobel_3x3_8_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_le16_16//c66//IMG_yc_demux_le16_16_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_clipping_16s//c66//IMG_clipping_16s_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_be16_16/IMG_yc_demux_be16_16.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_5x5_i8_c8s/IMG_conv_5x5_i8_c8s_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_5x5_16s/IMG_sobel_5x5_16s_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_be16_16/IMG_yc_demux_be16_16_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_wave_vert//c66//IMG_wave_vert_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_5x5_i16s_c16s/IMG_corr_5x5_i16s_c16s_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_dilate_bin//c66/IMG_dilate_bin.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_dilate_bin//c66/IMG_dilate_bin.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_11x11_i16s_c16s/IMG_conv_11x11_i16s_c16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_wave_vert/IMG_wave_vert_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_5x5_i8_c16s/IMG_conv_5x5_i8_c16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2thr_16//c66//IMG_thr_gt2thr_16_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_wave_vert/IMG_wave_vert_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_ycbcr422pl_to_rgb565/IMG_ycbcr422pl_to_rgb565_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2min_8/IMG_thr_le2min_8_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_be16_8/IMG_yc_demux_be16_8_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_median_3x3_16/IMG_median_3x3_16_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_gen_iq//c66//IMG_corr_gen_iq_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: docs/manifest/manifest.xml.xdt
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_7x7_i8_c8s//c66/IMG_conv_7x7_i8_c8s.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2max_8/IMG_thr_gt2max_8.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_pix_sat//c66//IMG_pix_sat_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_mad_16x16/IMG_mad_16x16.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_dilate_bin/IMG_dilate_bin_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_7x7_i8_c8s//c66/IMG_conv_7x7_i8_c8s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_dilate_bin/IMG_dilate_bin_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_quantize//c66/IMG_quantize.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2min_8//c66//IMG_thr_le2min_8_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_3x3_16s//c66/IMG_sobel_3x3_16s.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_3x3_16s//c66/IMG_sobel_3x3_16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_quantize//c66/IMG_quantize.s
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_pix_sat//c66//IMG_pix_sat_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_clipping_16s/IMG_clipping_16s_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_median_3x3_8/IMG_median_3x3_8_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_clipping_16s/IMG_clipping_16s_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2thr_8//c66//IMG_thr_le2thr_8_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_ycbcr422pl_to_rgb565//c66//IMG_ycbcr422pl_to_rgb565_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i8_c16s/IMG_corr_3x3_i8_c16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_gen_i16s_c16s//c66/IMG_corr_gen_i16s_c16s.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_3x3_8/IMG_sobel_3x3_8.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_5x5_16s//c66//IMG_sobel_5x5_16s_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_3x3_16/IMG_sobel_3x3_16_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_quantize/IMG_quantize.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_gen_i16s_c16s//c66/IMG_corr_gen_i16s_c16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sad_8x8//c66//IMG_sad_8x8_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i8_c8//c66//IMG_corr_3x3_i8_c8_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_erode_bin/IMG_erode_bin_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_3x3_i8_c8s/IMG_conv_3x3_i8_c8s_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_erode_bin/IMG_erode_bin_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_histogram_8/IMG_histogram_8_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2thr_16/IMG_thr_le2thr_16_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i8_c16s/IMG_corr_3x3_i8_c16s_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_ycbcr422pl_to_rgb565//c66//IMG_ycbcr422pl_to_rgb565_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i8_c8//c66//IMG_corr_3x3_i8_c8_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_3x3_i8_c8s//c66//IMG_conv_3x3_i8_c8s_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_le16_8/IMG_yc_demux_le16_8_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2thr_16//c66/IMG_thr_le2thr_16.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_median_3x3_16s/IMG_median_3x3_16s_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_gen_iq//c66//IMG_corr_gen_iq_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_le16_16/IMG_yc_demux_le16_16_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_dilate_bin/IMG_dilate_bin_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_histogram_16//c66//IMG_histogram_16_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_5x5_i16s_c16s/IMG_corr_5x5_i16s_c16s_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sad_16x16//c66//IMG_sad_16x16_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_wave_vert//c66//IMG_wave_vert_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_histogram_16/IMG_histogram_16.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_quantize//c66//IMG_quantize_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_idct_8x8_12q4/IMG_idct_8x8_12q4.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_pix_expand//c66/IMG_pix_expand.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_gen_i16s_c16s/IMG_corr_gen_i16s_c16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_mad_8x8//c66//IMG_mad_8x8_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_pix_expand//c66/IMG_pix_expand.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_3x3_i16s_c16s/IMG_conv_3x3_i16s_c16s_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sad_8x8//c66/IMG_sad_8x8.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_median_3x3_16//c66/IMG_median_3x3_16.sa
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2thr_8//c66/IMG_thr_le2thr_8.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_errdif_bin_16//c66/IMG_errdif_bin_16.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_perimeter_16/IMG_perimeter_16.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2thr_8//c66/IMG_thr_le2thr_8.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sad_8x8//c66/IMG_sad_8x8.s
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_3x3_i8_c8s//c66//IMG_conv_3x3_i8_c8s_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_wave_horz//c66/IMG_wave_horz.sa
ti_imglib_src_c66x_3_1_1_0.zip: ./src/common//c66/lnk.cmd
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_11x11_i8_c16s/IMG_corr_11x11_i8_c16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_5x5_16s/IMG_sobel_5x5_16s_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sad_8x8//c66//IMG_sad_8x8_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_11x11_i8_c8s/IMG_conv_11x11_i8_c8s_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i8_c16s//c66/IMG_corr_3x3_i8_c16s.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_7x7_i16s_c16s/IMG_conv_7x7_i16s_c16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_fdct_8x8//c66//IMG_fdct_8x8_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_fdct_8x8/IMG_fdct_8x8_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i8_c16s//c66/IMG_corr_3x3_i8_c16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_boundary_16s/IMG_boundary_16s_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_fdct_8x8/IMG_fdct_8x8_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_median_3x3_8/IMG_median_3x3_8_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_pix_expand/IMG_pix_expand_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_pix_expand/IMG_pix_expand_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_erode_bin//c66//IMG_erode_bin_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_3x3_16//c66/IMG_sobel_3x3_16.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_5x5_i16s_c16s/IMG_conv_5x5_i16s_c16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_le16_16/IMG_yc_demux_le16_16_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_le16_16/IMG_yc_demux_le16_16_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_boundary_8/IMG_boundary_8_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_dilate_bin/IMG_dilate_bin.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_be16_8/IMG_yc_demux_be16_8.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_clipping_16s//c66/IMG_clipping_16s.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_3x3_i16s_c16s//c66/IMG_conv_3x3_i16s_c16s.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_perimeter_8/IMG_perimeter_8_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_clipping_16s//c66/IMG_clipping_16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_3x3_i16s_c16s//c66/IMG_conv_3x3_i16s_c16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i8_c8/IMG_corr_3x3_i8_c8_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_7x7_i16s_c16s//c66//IMG_conv_7x7_i16s_c16s_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_3x3_16/IMG_sobel_3x3_16.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_11x11_i8_c8s/IMG_conv_11x11_i8_c8s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i16_c16//c66//IMG_corr_3x3_i16_c16_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_5x5_i16s_c16s//c66//IMG_corr_5x5_i16s_c16s_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2thr_16//c66/IMG_thr_gt2thr_16.sa
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_3x3_16s/IMG_sobel_3x3_16s_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_wave_vert//c66/IMG_wave_vert.sa
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_idct_8x8_12q4/IMG_idct_8x8_12q4_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2min_8/IMG_thr_le2min_8_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sad_16x16/IMG_sad_16x16_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2min_8/IMG_thr_le2min_8_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_7x7_i8_c8s//c66//IMG_conv_7x7_i8_c8s_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_histogram_8//c66/IMG_histogram_8.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_5x5_i8_c16s/IMG_conv_5x5_i8_c16s_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_11x11_i16s_c16s/IMG_corr_11x11_i16s_c16s_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_11x11_i8_c16s/IMG_corr_11x11_i8_c16s_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i16_c16//c66//IMG_corr_3x3_i16_c16_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_be16_8/IMG_yc_demux_be16_8_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_histogram_8//c66/IMG_histogram_8.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_pix_expand/IMG_pix_expand_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_fdct_8x8/IMG_fdct_8x8.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_5x5_i8_c8s//c66/IMG_conv_5x5_i8_c8s.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i8_c16s/IMG_corr_3x3_i8_c16s_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_3x3_16s/IMG_sobel_3x3_16s_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i16_c16/IMG_corr_3x3_i16_c16_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_7x7_i16s_c16s/IMG_conv_7x7_i16s_c16s_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2thr_16/IMG_thr_gt2thr_16_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_5x5_i8_c8s//c66/IMG_conv_5x5_i8_c8s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_boundary_16s/IMG_boundary_16s_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_3x3_16s/IMG_sobel_3x3_16s_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_7x7_i16s_c16s/IMG_conv_7x7_i16s_c16s_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2thr_16/IMG_thr_gt2thr_16_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2thr_8/IMG_thr_le2thr_8_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_boundary_16s/IMG_boundary_16s_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_wave_horz/IMG_wave_horz_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_boundary_8/IMG_boundary_8.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_be16_16/IMG_yc_demux_be16_16_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_11x11_i8_c16s//c66//IMG_corr_11x11_i8_c16s_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_be16_16/IMG_yc_demux_be16_16_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_le16_16/IMG_yc_demux_le16_16.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2max_16//c66/IMG_thr_gt2max_16.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_gen_iq/IMG_corr_gen_iq_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_11x11_i8_c16s/IMG_corr_11x11_i8_c16s_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_errdif_bin_16/IMG_errdif_bin_16.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_clipping_16s/IMG_clipping_16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_le16_16//c66/IMG_yc_demux_le16_16.sa
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_perimeter_8/IMG_perimeter_8_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_5x5_i16s_c16s//c66//IMG_conv_5x5_i16s_c16s_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_dilate_bin/IMG_dilate_bin_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_3x3_i16_c16s//c66/IMG_conv_3x3_i16_c16s.sa
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_perimeter_8/IMG_perimeter_8_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_3x3_i8_c8s//c66/IMG_conv_3x3_i8_c8s.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_3x3_i8_c8s//c66/IMG_conv_3x3_i8_c8s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_median_3x3_16s/IMG_median_3x3_16s_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_11x11_i8_c16s//c66//IMG_corr_11x11_i8_c16s_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_median_3x3_16s/IMG_median_3x3_16s_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_gen_i16s_c16s//c66//IMG_corr_gen_i16s_c16s_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/common/IMG_memory.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_histogram_16/IMG_histogram_16_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2thr_16/IMG_thr_le2thr_16.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2max_8/IMG_thr_gt2max_8_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/common/IMG_profile.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/common/IMG_memory.h
ti_imglib_src_c66x_3_1_1_0.zip: package/package.cfg.xdc.inc
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_errdif_bin_16/IMG_errdif_bin_16_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/common/IMG_profile.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_7x7_16s/IMG_sobel_7x7_16s_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2min_16//c66//IMG_thr_le2min_16_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i8_c16s//c66//IMG_corr_3x3_i8_c16s_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_boundary_8/IMG_boundary_8_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_boundary_8//c66//IMG_boundary_8_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_5x5_i8_c8s/IMG_conv_5x5_i8_c8s_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_boundary_8/IMG_boundary_8_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2max_16/IMG_thr_gt2max_16_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_wave_vert//c66/IMG_wave_vert.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i16s_c16s//c66//IMG_corr_3x3_i16s_c16s_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_pix_sat/IMG_pix_sat_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_median_3x3_16/IMG_median_3x3_16_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_gen_iq/IMG_corr_gen_iq_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_pix_sat/IMG_pix_sat_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_median_3x3_16/IMG_median_3x3_16_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_gen_iq/IMG_corr_gen_iq_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sad_16x16/IMG_sad_16x16_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_5x5_i16s_c16s/IMG_corr_5x5_i16s_c16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sad_16x16/IMG_sad_16x16_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_11x11_i16s_c16s/IMG_conv_11x11_i16s_c16s_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_3x3_i16s_c16s/IMG_conv_3x3_i16s_c16s_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2thr_8//c66//IMG_thr_gt2thr_8_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2thr_16/IMG_thr_gt2thr_16.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_histogram_8/IMG_histogram_8_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_5x5_i8_c8s/IMG_conv_5x5_i8_c8s_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_pix_expand/IMG_pix_expand_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_erode_bin//c66//IMG_erode_bin_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_3x3_i16s_c16s//c66//IMG_conv_3x3_i16s_c16s_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_5x5_i8_c8s/IMG_conv_5x5_i8_c8s_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i16s_c16s/IMG_corr_3x3_i16s_c16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_boundary_16s/IMG_boundary_16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_3x3_i16s_c16s/IMG_conv_3x3_i16s_c16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_erode_bin/IMG_erode_bin_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_7x7_i8_c8s/IMG_conv_7x7_i8_c8s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_5x5_i16s_c16s//c66//IMG_corr_5x5_i16s_c16s_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_quantize//c66//IMG_quantize_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_7x7_i8_c16s//c66//IMG_conv_7x7_i8_c16s_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_errdif_bin_8/IMG_errdif_bin_8_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2min_16//c66//IMG_thr_le2min_16_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_5x5_i16s_c16s//c66/IMG_conv_5x5_i16s_c16s.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/common/IMG_utility.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_5x5_i16s_c16s//c66/IMG_conv_5x5_i16s_c16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_11x11_i8_c16s//c66/IMG_corr_11x11_i8_c16s.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/common/IMG_utility.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2min_8/IMG_thr_le2min_8_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_7x7_i8_c8s/IMG_conv_7x7_i8_c8s_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_11x11_i8_c16s//c66/IMG_corr_11x11_i8_c16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_5x5_i16s_c16s/IMG_conv_5x5_i16s_c16s_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_be16_8//c66/IMG_yc_demux_be16_8.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_7x7_i16s_c16s//c66/IMG_conv_7x7_i16s_c16s.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_5x5_i16s_c16s/IMG_conv_5x5_i16s_c16s_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_be16_8//c66/IMG_yc_demux_be16_8.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_7x7_i16s_c16s//c66/IMG_conv_7x7_i16s_c16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_histogram_16//c66/IMG_histogram_16.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_median_3x3_16s//c66//IMG_median_3x3_16s_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_mad_8x8/IMG_mad_8x8_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2max_8//c66//IMG_thr_gt2max_8_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_histogram_16//c66/IMG_histogram_16.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_3x3_8//c66/IMG_sobel_3x3_8.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2min_8//c66//IMG_thr_le2min_8_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_5x5_16s/IMG_sobel_5x5_16s_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_3x3_8//c66/IMG_sobel_3x3_8.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_11x11_i16s_c16s//c66//IMG_conv_11x11_i16s_c16s_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: package/package.xdc.inc
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_perimeter_16/IMG_perimeter_16_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_3x3_i16_c16s/IMG_conv_3x3_i16_c16s_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_5x5_16s/IMG_sobel_5x5_16s_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_3x3_i16_c16s/IMG_conv_3x3_i16_c16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_erode_bin//c66/IMG_erode_bin.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_7x7_16s//c66//IMG_sobel_7x7_16s_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_3x3_i8_c8s/IMG_conv_3x3_i8_c8s_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2thr_16//c66/IMG_thr_gt2thr_16.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_3x3_8/IMG_sobel_3x3_8_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_pix_sat/IMG_pix_sat_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_erode_bin//c66/IMG_erode_bin.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2min_8//c66/IMG_thr_le2min_8.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_3x3_8//c66//IMG_sobel_3x3_8_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_3x3_8/IMG_sobel_3x3_8_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2min_8//c66/IMG_thr_le2min_8.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_clipping_16s/IMG_clipping_16s_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_3x3_16s//c66//IMG_sobel_3x3_16s_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_11x11_i16s_c16s/IMG_conv_11x11_i16s_c16s_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_5x5_i16s_c16s/IMG_conv_5x5_i16s_c16s_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_11x11_i16s_c16s/IMG_conv_11x11_i16s_c16s_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_mad_16x16//c66//IMG_mad_16x16_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2min_16//c66/IMG_thr_le2min_16.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_median_3x3_16s//c66/IMG_median_3x3_16s.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_wave_vert/IMG_wave_vert_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_median_3x3_16s//c66/IMG_median_3x3_16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_3x3_i16_c16s/IMG_conv_3x3_i16_c16s_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_erode_bin/IMG_erode_bin_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_11x11_i16s_c16s/IMG_conv_11x11_i16s_c16s_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_3x3_i16_c16s/IMG_conv_3x3_i16_c16s_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: makefile
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_11x11_i16s_c16s//c66/IMG_conv_11x11_i16s_c16s.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_idct_8x8_12q4/IMG_idct_8x8_12q4_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_5x5_i8_c8s/IMG_conv_5x5_i8_c8s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_11x11_i16s_c16s//c66/IMG_conv_11x11_i16s_c16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_7x7_i16s_c16s/IMG_conv_7x7_i16s_c16s_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2max_16//c66//IMG_thr_gt2max_16_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i16s_c16s//c66//IMG_corr_3x3_i16s_c16s_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_errdif_bin_8/IMG_errdif_bin_8.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_boundary_16s/IMG_boundary_16s_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_pix_sat//c66/IMG_pix_sat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i8_c8/IMG_corr_3x3_i8_c8.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_pix_expand/IMG_pix_expand.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_pix_sat/IMG_pix_sat_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_fdct_8x8/IMG_fdct_8x8_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_pix_sat//c66/IMG_pix_sat.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2min_16//c66/IMG_thr_le2min_16.sa
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_wave_horz/IMG_wave_horz.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_perimeter_8/IMG_perimeter_8_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_be16_16//c66/IMG_yc_demux_be16_16.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_histogram_16/IMG_histogram_16_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_7x7_16s/IMG_sobel_7x7_16s_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_7x7_i8_c16s/IMG_conv_7x7_i8_c16s_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_histogram_16/IMG_histogram_16_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_7x7_16s//c66//IMG_sobel_7x7_16s_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2max_16/IMG_thr_gt2max_16_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_le16_8//c66//IMG_yc_demux_le16_8_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_mad_8x8/IMG_mad_8x8.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2min_16/IMG_thr_le2min_16_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2max_16//c66/IMG_thr_gt2max_16.sa
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i16s_c16s/IMG_corr_3x3_i16s_c16s_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_histogram_16/IMG_histogram_16_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_perimeter_16/IMG_perimeter_16_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2thr_16/IMG_thr_le2thr_16_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_3x3_i16s_c16s//c66//IMG_conv_3x3_i16s_c16s_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_3x3_i16_c16s/IMG_conv_3x3_i16_c16s_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_boundary_16s//c66//IMG_boundary_16s_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_perimeter_16/IMG_perimeter_16_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i16s_c16s/IMG_corr_3x3_i16s_c16s_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2thr_8//c66/IMG_thr_gt2thr_8.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2thr_16/IMG_thr_gt2thr_16_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_idct_8x8_12q4/IMG_idct_8x8_12q4_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sad_8x8/IMG_sad_8x8_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2thr_8//c66/IMG_thr_gt2thr_8.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_idct_8x8_12q4/IMG_idct_8x8_12q4_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sad_16x16//c66//IMG_sad_16x16_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_11x11_i8_c8s/IMG_conv_11x11_i8_c8s_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i8_c8/IMG_corr_3x3_i8_c8_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_3x3_i8_c8s/IMG_conv_3x3_i8_c8s.h
ti_imglib_src_c66x_3_1_1_0.zip: Makedocs.mk
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_5x5_16s/IMG_sobel_5x5_16s_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i8_c8/IMG_corr_3x3_i8_c8_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_be16_16/IMG_yc_demux_be16_16_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_idct_8x8_12q4//c66//IMG_idct_8x8_12q4_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_5x5_i16s_c16s/IMG_corr_5x5_i16s_c16s_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_3x3_i16s_c16s/IMG_conv_3x3_i16s_c16s_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_11x11_i16s_c16s/IMG_corr_11x11_i16s_c16s_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_perimeter_8//c66/IMG_perimeter_8.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_3x3_i16s_c16s/IMG_conv_3x3_i16s_c16s_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i8_c16s/IMG_corr_3x3_i8_c16s_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_11x11_i16s_c16s/IMG_corr_11x11_i16s_c16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_perimeter_8//c66/IMG_perimeter_8.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_perimeter_16/IMG_perimeter_16_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i8_c16s/IMG_corr_3x3_i8_c16s_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_gen_i16s_c16s/IMG_corr_gen_i16s_c16s_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i16_c16/IMG_corr_3x3_i16_c16_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_boundary_16s//c66//IMG_boundary_16s_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_ycbcr422pl_to_rgb565/IMG_ycbcr422pl_to_rgb565_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_gt2thr_8/IMG_thr_gt2thr_8_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_5x5_i16s_c16s//c66//IMG_conv_5x5_i16s_c16s_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_11x11_i8_c8s//c66/IMG_conv_11x11_i8_c8s.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_median_3x3_16/IMG_median_3x3_16_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_11x11_i8_c8s//c66/IMG_conv_11x11_i8_c8s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_gen_iq/IMG_corr_gen_iq_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_3x3_16/IMG_sobel_3x3_16_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sad_16x16/IMG_sad_16x16.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_errdif_bin_8//c66/IMG_errdif_bin_8.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2thr_16//c66/IMG_thr_le2thr_16.sa
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_7x7_16s/IMG_sobel_7x7_16s_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_errdif_bin_8//c66/IMG_errdif_bin_8.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_7x7_16s/IMG_sobel_7x7_16s_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_3x3_8/IMG_sobel_3x3_8_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_11x11_i16s_c16s/IMG_corr_11x11_i16s_c16s_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_11x11_i16s_c16s/IMG_corr_11x11_i16s_c16s_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: docs/bundle/manifest/doxyfile.xdt
ti_imglib_src_c66x_3_1_1_0.zip: package/package.ext.xml
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_sobel_3x3_8//c66//IMG_sobel_3x3_8_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_pix_expand//c66//IMG_pix_expand_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_7x7_i16s_c16s//c66//IMG_conv_7x7_i16s_c16s_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_7x7_i8_c8s//c66//IMG_conv_7x7_i8_c8s_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_7x7_i16s_c16s/IMG_conv_7x7_i16s_c16s_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_quantize/IMG_quantize_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_11x11_i8_c8s//c66//IMG_conv_11x11_i8_c8s_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_be16_8/IMG_yc_demux_be16_8_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2min_8/IMG_thr_le2min_8.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_histogram_16//c66//IMG_histogram_16_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2min_16/IMG_thr_le2min_16_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_thr_le2thr_8/IMG_thr_le2thr_8_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i16s_c16s//c66/IMG_corr_3x3_i16s_c16s.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_11x11_i8_c8s/IMG_conv_11x11_i8_c8s_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_histogram_8/IMG_histogram_8_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i16s_c16s//c66/IMG_corr_3x3_i16s_c16s.h
ti_imglib_src_c66x_3_1_1_0.zip: package/package.bld.xml
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_mad_8x8/IMG_mad_8x8_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_mad_8x8/IMG_mad_8x8_cn.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i8_c16s/IMG_corr_3x3_i8_c16s_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_5x5_i16s_c16s//c66/IMG_corr_5x5_i16s_c16s.c
ti_imglib_src_c66x_3_1_1_0.zip: package.bld
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_clipping_16s/IMG_clipping_16s_d.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_wave_horz//c66/IMG_wave_horz.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_5x5_i16s_c16s//c66/IMG_corr_5x5_i16s_c16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_clipping_16s//c66//IMG_clipping_16s_66_LE_ELF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_fdct_8x8//c66/IMG_fdct_8x8.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_median_3x3_16//c66//IMG_median_3x3_16_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_median_3x3_16s/IMG_median_3x3_16s_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_dilate_bin/IMG_dilate_bin_odat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_median_3x3_8/IMG_median_3x3_8_idat.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_conv_5x5_i8_c8s//c66//IMG_conv_5x5_i8_c8s_66_LE_COFF
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_fdct_8x8//c66/IMG_fdct_8x8.s
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_11x11_i16s_c16s//c66/IMG_corr_11x11_i16s_c16s.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_11x11_i16s_c16s//c66/IMG_corr_11x11_i16s_c16s.h
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i16_c16/IMG_corr_3x3_i16_c16_cn.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_gen_iq//c66/IMG_corr_gen_iq.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_yc_demux_le16_8//c66/IMG_yc_demux_le16_8.c
ti_imglib_src_c66x_3_1_1_0.zip: ./src/IMG_corr_3x3_i16_c16/IMG_corr_3x3_i16_c16_cn.h
ifneq (clean,$(MAKECMDGOALS))
-include package/rel/ti_imglib_src_c66x_3_1_1_0.zip.dep
endif
package/rel/ti_imglib_src_c66x_3_1_1_0/ti/imglib/package/package.rel.xml:

ti_imglib_src_c66x_3_1_1_0.zip: package/rel/ti_imglib_src_c66x_3_1_1_0.xdc.inc package/rel/ti_imglib_src_c66x_3_1_1_0/ti/imglib/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELZIP,package/rel/ti_imglib_src_c66x_3_1_1_0.xdc.inc,package/rel/ti_imglib_src_c66x_3_1_1_0.zip.dep)


release release,ti_imglib_src_c66x_3_1_1_0: all ti_imglib_src_c66x_3_1_1_0.zip
clean:: .clean
	-$(RM) ti_imglib_src_c66x_3_1_1_0.zip
	-$(RM) package/rel/ti_imglib_src_c66x_3_1_1_0.xdc.inc
	-$(RM) package/rel/ti_imglib_src_c66x_3_1_1_0.zip.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#
	-$(RM) Version.xdc
	-$(RM) Version.h
	-$(RM) makefile

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package


all: IMGLIB_CCSV5
IMGLIB_CCSV5: .xdcenv.mak Package.bld Package.mak
	"$(CCSV5_INSTALL_DIR)/eclipse/eclipsec.exe" -noSplash  -data "C:/Temp/workspace" -application com.ti.ccstudio.apps.projectCreate -ccs.autoGenerateMakefiles false -ccs.device com.ti.ccstudio.deviceModel.C6000.CustomC6000Device -ccs.buildCommandFlags CCSVERSION=${CCSVERSION} -ccs.name IMGLIB -ccs.location ../../../lib -ccs.linkFile EXT_ROOT__IMGLIB/makefile -ccs.overwrite keep -ccs.buildFlags CCSVERSION=${CCSVERSION} -ccs.definePathVariable EXT_ROOT__IMGLIB C:/builds/IMGLIB/TI_PRODUCT_3_1_1_0/imglib/ti/imglib/imglib/packages/ti/imglib -ccs.defineBuildVariable PROJECT_ROOT_PARENT '$${PROJECT_ROOT}/..' @scope project -ccs.buildLocation '$${PROJECT_ROOT_PARENT}/./packages/ti/imglib'
	echo EXT_ROOT__IMGLIB=../packages/ti/imglib > ../../../lib/macros.ini
	-$(RMDIR) "C:/Temp/workspace"


all: IMGLIB_CCSV4
IMGLIB_CCSV4: .xdcenv.mak Package.bld Package.mak
	java -jar "$(CCSV4_INSTALL_DIR)/eclipse/startup.jar"  -data "C:/Temp/workspace" -application com.ti.ccstudio.apps.projectCreate_stdMake -ccs.name IMGLIB -ccs.location ../../../lib -ccs.linkFile EXT_ROOT__IMGLIB/makefile -ccs.overwrite keep -ccs.buildFlags CCSVERSION=${CCSVERSION} -ccs.definePathVariable EXT_ROOT__IMGLIB C:/builds/IMGLIB/TI_PRODUCT_3_1_1_0/imglib/ti/imglib/imglib/packages/ti/imglib -ccs.buildLocation '$${PROJECT_ROOT}/../packages/ti/imglib'
	-$(RMDIR) "C:/Temp/workspace"

clean::
	-$(RM)  *.zip
clean::
	-$(RM)  *.bin
clean::
	-$(RM)  *.exe
clean::
	-$(RM)  .//docs//doxygen//*.chm
clean::
	-$(RM)  .//docs/*.chm
clean::
	-$(RMDIR) .//docs//doxygen//html
clean::
	-$(RMDIR) cov_out
clean::
	-$(RMDIR) c54
clean::
	-$(RMDIR) c54f
clean::
	-$(RMDIR) c55
clean::
	-$(RMDIR) c55l
clean::
	-$(RMDIR) c64
clean::
	-$(RMDIR) c64e
clean::
	-$(RMDIR) c674
clean::
	-$(RMDIR) c674e
clean::
	-$(RMDIR) ce66
clean::
	-$(RMDIR) ce66e
clean::
	-$(RMDIR) c64P
clean::
	-$(RMDIR) c64Pe
clean::
	-$(RMDIR) mvarm9
clean::
	-$(RMDIR) gcarmv6
clean::
	-$(RMDIR) gcarmv7a
clean::
	-$(RMDIR) wince
clean::
	-$(RMDIR) tiarmv6le
clean::
	-$(RMDIR) tiarmv6be

