#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = ti/sdo/edma3/drv
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/utils.js:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/utils.js
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/xdc.tci:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/xdc.tci
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/template.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/template.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/om2.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/om2.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/xmlgen.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/xmlgen.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/xmlgen2.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/xmlgen2.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/Warnings.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/Warnings.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/IPackage.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/IPackage.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/package.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/package.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/services/global/Clock.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/services/global/Clock.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/services/global/Trace.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/services/global/Trace.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/bld.js:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/bld.js
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/BuildEnvironment.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/PackageContents.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/PackageContents.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/_gen.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/_gen.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/Library.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/Library.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/Executable.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/Executable.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/Repository.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/Repository.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/Configuration.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/Configuration.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/Script.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/Script.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/Manifest.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/Manifest.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/Utils.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/Utils.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/ITarget.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/ITarget.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/ITarget2.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/ITarget2.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/ITarget3.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/ITarget3.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/ITargetFilter.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/ITargetFilter.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/package.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-xdctools-tree/packages/xdc/bld/package.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/work/am57xx_evm-linux-gnueabi/edma3-lld-rtos/2.12.02.26-r0.0/git/packages/config.bld:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/work/am57xx_evm-linux-gnueabi/edma3-lld-rtos/2.12.02.26-r0.0/git/packages/config.bld
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/ITarget.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/ITarget.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/C28_large.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/C28_large.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/C28_float.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/C28_float.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/package.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/package.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/elf/ITarget.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/elf/ITarget.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/elf/package.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/elf/package.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/arm/elf/IArm.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/arm/elf/IArm.xs
/home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/arm/elf/package.xs:
package.mak: /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/arm/elf/package.xs
package.mak: package.bld
endif

ti.targets.C64P.rootDir ?= /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/x86_64-linux/usr/share/ti/cgt-c6x
ti.targets.packageBase ?= /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/
ti.targets.C64P_big_endian.rootDir ?= /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/x86_64-linux/usr/share/ti/cgt-c6x
ti.targets.C674.rootDir ?= /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/x86_64-linux/usr/share/ti/cgt-c6x
ti.targets.elf.C64P.rootDir ?= /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/x86_64-linux/usr/share/ti/cgt-c6x
ti.targets.elf.packageBase ?= /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/elf/
ti.targets.elf.C64P_big_endian.rootDir ?= /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/x86_64-linux/usr/share/ti/cgt-c6x
ti.targets.elf.C674.rootDir ?= /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/x86_64-linux/usr/share/ti/cgt-c6x
ti.targets.elf.C66.rootDir ?= /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/x86_64-linux/usr/share/ti/cgt-c6x
ti.targets.elf.C66_big_endian.rootDir ?= /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/x86_64-linux/usr/share/ti/cgt-c6x
ti.targets.arm.elf.Arm9.rootDir ?= /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/x86_64-linux/usr/share/ti/ti-cgt-arm
ti.targets.arm.elf.packageBase ?= /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/am57xx-evm/usr/share/ti/ti-sysbios-tree/packages/ti/targets/arm/elf/
ti.targets.arm.elf.A8F.rootDir ?= /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/x86_64-linux/usr/share/ti/ti-cgt-arm
ti.targets.arm.elf.M3.rootDir ?= /home/gtbldadm/processor-sdk-linux-krogoth-build/build-CORTEX_1/arago-tmp-external-linaro-toolchain/sysroots/x86_64-linux/usr/share/ti/ti-cgt-arm
.PRECIOUS: $(XDCCFGDIR)/%.o64P
.PHONY: all,64P .dlls,64P .executables,64P test,64P
all,64P: .executables,64P
.executables,64P: .libraries,64P
.executables,64P: .dlls,64P
.dlls,64P: .libraries,64P
.libraries,64P: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,64P
	@$(ECHO) xdc .executables,64P
	@$(ECHO) xdc .libraries,64P
	@$(ECHO) xdc .dlls,64P

.PRECIOUS: $(XDCCFGDIR)/%.o64Pe
.PHONY: all,64Pe .dlls,64Pe .executables,64Pe test,64Pe
all,64Pe: .executables,64Pe
.executables,64Pe: .libraries,64Pe
.executables,64Pe: .dlls,64Pe
.dlls,64Pe: .libraries,64Pe
.libraries,64Pe: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,64Pe
	@$(ECHO) xdc .executables,64Pe
	@$(ECHO) xdc .libraries,64Pe
	@$(ECHO) xdc .dlls,64Pe

.PRECIOUS: $(XDCCFGDIR)/%.o674
.PHONY: all,674 .dlls,674 .executables,674 test,674
all,674: .executables,674
.executables,674: .libraries,674
.executables,674: .dlls,674
.dlls,674: .libraries,674
.libraries,674: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,674
	@$(ECHO) xdc .executables,674
	@$(ECHO) xdc .libraries,674
	@$(ECHO) xdc .dlls,674

.PRECIOUS: $(XDCCFGDIR)/%.oe64P
.PHONY: all,e64P .dlls,e64P .executables,e64P test,e64P
all,e64P: .executables,e64P
.executables,e64P: .libraries,e64P
.executables,e64P: .dlls,e64P
.dlls,e64P: .libraries,e64P
.libraries,e64P: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,e64P
	@$(ECHO) xdc .executables,e64P
	@$(ECHO) xdc .libraries,e64P
	@$(ECHO) xdc .dlls,e64P

.PRECIOUS: $(XDCCFGDIR)/%.oe64Pe
.PHONY: all,e64Pe .dlls,e64Pe .executables,e64Pe test,e64Pe
all,e64Pe: .executables,e64Pe
.executables,e64Pe: .libraries,e64Pe
.executables,e64Pe: .dlls,e64Pe
.dlls,e64Pe: .libraries,e64Pe
.libraries,e64Pe: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,e64Pe
	@$(ECHO) xdc .executables,e64Pe
	@$(ECHO) xdc .libraries,e64Pe
	@$(ECHO) xdc .dlls,e64Pe

.PRECIOUS: $(XDCCFGDIR)/%.oe674
.PHONY: all,e674 .dlls,e674 .executables,e674 test,e674
all,e674: .executables,e674
.executables,e674: .libraries,e674
.executables,e674: .dlls,e674
.dlls,e674: .libraries,e674
.libraries,e674: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,e674
	@$(ECHO) xdc .executables,e674
	@$(ECHO) xdc .libraries,e674
	@$(ECHO) xdc .dlls,e674

.PRECIOUS: $(XDCCFGDIR)/%.oe66
.PHONY: all,e66 .dlls,e66 .executables,e66 test,e66
all,e66: .executables,e66
.executables,e66: .libraries,e66
.executables,e66: .dlls,e66
.dlls,e66: .libraries,e66
.libraries,e66: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,e66
	@$(ECHO) xdc .executables,e66
	@$(ECHO) xdc .libraries,e66
	@$(ECHO) xdc .dlls,e66

.PRECIOUS: $(XDCCFGDIR)/%.oe66e
.PHONY: all,e66e .dlls,e66e .executables,e66e test,e66e
all,e66e: .executables,e66e
.executables,e66e: .libraries,e66e
.executables,e66e: .dlls,e66e
.dlls,e66e: .libraries,e66e
.libraries,e66e: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,e66e
	@$(ECHO) xdc .executables,e66e
	@$(ECHO) xdc .libraries,e66e
	@$(ECHO) xdc .dlls,e66e

.PRECIOUS: $(XDCCFGDIR)/%.oe9
.PHONY: all,e9 .dlls,e9 .executables,e9 test,e9
all,e9: .executables,e9
.executables,e9: .libraries,e9
.executables,e9: .dlls,e9
.dlls,e9: .libraries,e9
.libraries,e9: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,e9
	@$(ECHO) xdc .executables,e9
	@$(ECHO) xdc .libraries,e9
	@$(ECHO) xdc .dlls,e9

.PRECIOUS: $(XDCCFGDIR)/%.oea8f
.PHONY: all,ea8f .dlls,ea8f .executables,ea8f test,ea8f
all,ea8f: .executables,ea8f
.executables,ea8f: .libraries,ea8f
.executables,ea8f: .dlls,ea8f
.dlls,ea8f: .libraries,ea8f
.libraries,ea8f: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,ea8f
	@$(ECHO) xdc .executables,ea8f
	@$(ECHO) xdc .libraries,ea8f
	@$(ECHO) xdc .dlls,ea8f

.PRECIOUS: $(XDCCFGDIR)/%.oem3
.PHONY: all,em3 .dlls,em3 .executables,em3 test,em3
all,em3: .executables,em3
.executables,em3: .libraries,em3
.executables,em3: .dlls,em3
.dlls,em3: .libraries,em3
.libraries,em3: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,em3
	@$(ECHO) xdc .executables,em3
	@$(ECHO) xdc .libraries,em3
	@$(ECHO) xdc .dlls,em3


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_ti.sdo.edma3.drv.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package ti.sdo.edma3.drv" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

ifeq (,$(MK_NOGENDEPS))
-include package/package.cfg.dep
endif

package/package.cfg.xdc.inc: .interfaces $(XDCROOT)/packages/xdc/cfg/cfginc.js package.xdc
	@$(MSG) generating schema include file list ...
	$(CONFIG) -f $(XDCROOT)/packages/xdc/cfg/cfginc.js ti.sdo.edma3.drv $@

.libraries,64P .libraries: lib/64p/debug/ti.sdo.edma3.drv.a64P

-include lib/64p/debug/ti.sdo.edma3.drv.a64P.mak
lib/64p/debug/ti.sdo.edma3.drv.a64P: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/64p/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.o64P package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_init.o64P package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.o64P package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.o64P  into $@ ...
	$(ti.targets.C64P.rootDir)/bin/ar6x  rq $@   package/lib/lib/64p/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.o64P package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_init.o64P package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.o64P package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.o64P 
lib/64p/debug/ti.sdo.edma3.drv.a64P: export C_DIR=
lib/64p/debug/ti.sdo.edma3.drv.a64P: PATH:=$(ti.targets.C64P.rootDir)/bin/:$(PATH)

clean,64P clean::
	-$(RM) lib/64p/debug/ti.sdo.edma3.drv.a64P
.libraries,64P .libraries: lib/64p/release/ti.sdo.edma3.drv.a64P

-include lib/64p/release/ti.sdo.edma3.drv.a64P.mak
lib/64p/release/ti.sdo.edma3.drv.a64P: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/64p/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.o64P package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_init.o64P package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_basic.o64P package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_adv.o64P  into $@ ...
	$(ti.targets.C64P.rootDir)/bin/ar6x  rq $@   package/lib/lib/64p/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.o64P package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_init.o64P package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_basic.o64P package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_adv.o64P 
lib/64p/release/ti.sdo.edma3.drv.a64P: export C_DIR=
lib/64p/release/ti.sdo.edma3.drv.a64P: PATH:=$(ti.targets.C64P.rootDir)/bin/:$(PATH)

clean,64P clean::
	-$(RM) lib/64p/release/ti.sdo.edma3.drv.a64P
.libraries,64Pe .libraries: lib/64p/debug/ti.sdo.edma3.drv.a64Pe

-include lib/64p/debug/ti.sdo.edma3.drv.a64Pe.mak
lib/64p/debug/ti.sdo.edma3.drv.a64Pe: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/64p/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.o64Pe package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_init.o64Pe package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.o64Pe package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.o64Pe  into $@ ...
	$(ti.targets.C64P_big_endian.rootDir)/bin/ar6x  rq $@   package/lib/lib/64p/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.o64Pe package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_init.o64Pe package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.o64Pe package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.o64Pe 
lib/64p/debug/ti.sdo.edma3.drv.a64Pe: export C_DIR=
lib/64p/debug/ti.sdo.edma3.drv.a64Pe: PATH:=$(ti.targets.C64P_big_endian.rootDir)/bin/:$(PATH)

clean,64Pe clean::
	-$(RM) lib/64p/debug/ti.sdo.edma3.drv.a64Pe
.libraries,64Pe .libraries: lib/64p/release/ti.sdo.edma3.drv.a64Pe

-include lib/64p/release/ti.sdo.edma3.drv.a64Pe.mak
lib/64p/release/ti.sdo.edma3.drv.a64Pe: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/64p/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.o64Pe package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_init.o64Pe package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_basic.o64Pe package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_adv.o64Pe  into $@ ...
	$(ti.targets.C64P_big_endian.rootDir)/bin/ar6x  rq $@   package/lib/lib/64p/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.o64Pe package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_init.o64Pe package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_basic.o64Pe package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_adv.o64Pe 
lib/64p/release/ti.sdo.edma3.drv.a64Pe: export C_DIR=
lib/64p/release/ti.sdo.edma3.drv.a64Pe: PATH:=$(ti.targets.C64P_big_endian.rootDir)/bin/:$(PATH)

clean,64Pe clean::
	-$(RM) lib/64p/release/ti.sdo.edma3.drv.a64Pe
.libraries,674 .libraries: lib/674/debug/ti.sdo.edma3.drv.a674

-include lib/674/debug/ti.sdo.edma3.drv.a674.mak
lib/674/debug/ti.sdo.edma3.drv.a674: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/674/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.o674 package/lib/lib/674/debug/ti.sdo.edma3.drv/src/edma3_drv_init.o674 package/lib/lib/674/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.o674 package/lib/lib/674/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.o674  into $@ ...
	$(ti.targets.C674.rootDir)/bin/ar6x  rq $@   package/lib/lib/674/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.o674 package/lib/lib/674/debug/ti.sdo.edma3.drv/src/edma3_drv_init.o674 package/lib/lib/674/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.o674 package/lib/lib/674/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.o674 
lib/674/debug/ti.sdo.edma3.drv.a674: export C_DIR=
lib/674/debug/ti.sdo.edma3.drv.a674: PATH:=$(ti.targets.C674.rootDir)/bin/:$(PATH)

clean,674 clean::
	-$(RM) lib/674/debug/ti.sdo.edma3.drv.a674
.libraries,674 .libraries: lib/674/release/ti.sdo.edma3.drv.a674

-include lib/674/release/ti.sdo.edma3.drv.a674.mak
lib/674/release/ti.sdo.edma3.drv.a674: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/674/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.o674 package/lib/lib/674/release/ti.sdo.edma3.drv/src/edma3_drv_init.o674 package/lib/lib/674/release/ti.sdo.edma3.drv/src/edma3_drv_basic.o674 package/lib/lib/674/release/ti.sdo.edma3.drv/src/edma3_drv_adv.o674  into $@ ...
	$(ti.targets.C674.rootDir)/bin/ar6x  rq $@   package/lib/lib/674/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.o674 package/lib/lib/674/release/ti.sdo.edma3.drv/src/edma3_drv_init.o674 package/lib/lib/674/release/ti.sdo.edma3.drv/src/edma3_drv_basic.o674 package/lib/lib/674/release/ti.sdo.edma3.drv/src/edma3_drv_adv.o674 
lib/674/release/ti.sdo.edma3.drv.a674: export C_DIR=
lib/674/release/ti.sdo.edma3.drv.a674: PATH:=$(ti.targets.C674.rootDir)/bin/:$(PATH)

clean,674 clean::
	-$(RM) lib/674/release/ti.sdo.edma3.drv.a674
.libraries,e64P .libraries: lib/64p/debug/ti.sdo.edma3.drv.ae64P

-include lib/64p/debug/ti.sdo.edma3.drv.ae64P.mak
lib/64p/debug/ti.sdo.edma3.drv.ae64P: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/64p/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe64P package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_init.oe64P package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.oe64P package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.oe64P  into $@ ...
	$(ti.targets.elf.C64P.rootDir)/bin/ar6x  rq $@   package/lib/lib/64p/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe64P package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_init.oe64P package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.oe64P package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.oe64P 
lib/64p/debug/ti.sdo.edma3.drv.ae64P: export C_DIR=
lib/64p/debug/ti.sdo.edma3.drv.ae64P: PATH:=$(ti.targets.elf.C64P.rootDir)/bin/:$(PATH)

clean,e64P clean::
	-$(RM) lib/64p/debug/ti.sdo.edma3.drv.ae64P
.libraries,e64P .libraries: lib/64p/release/ti.sdo.edma3.drv.ae64P

-include lib/64p/release/ti.sdo.edma3.drv.ae64P.mak
lib/64p/release/ti.sdo.edma3.drv.ae64P: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/64p/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe64P package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_init.oe64P package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_basic.oe64P package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_adv.oe64P  into $@ ...
	$(ti.targets.elf.C64P.rootDir)/bin/ar6x  rq $@   package/lib/lib/64p/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe64P package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_init.oe64P package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_basic.oe64P package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_adv.oe64P 
lib/64p/release/ti.sdo.edma3.drv.ae64P: export C_DIR=
lib/64p/release/ti.sdo.edma3.drv.ae64P: PATH:=$(ti.targets.elf.C64P.rootDir)/bin/:$(PATH)

clean,e64P clean::
	-$(RM) lib/64p/release/ti.sdo.edma3.drv.ae64P
.libraries,e64Pe .libraries: lib/64p/debug/ti.sdo.edma3.drv.ae64Pe

-include lib/64p/debug/ti.sdo.edma3.drv.ae64Pe.mak
lib/64p/debug/ti.sdo.edma3.drv.ae64Pe: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/64p/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe64Pe package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_init.oe64Pe package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.oe64Pe package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.oe64Pe  into $@ ...
	$(ti.targets.elf.C64P_big_endian.rootDir)/bin/ar6x  rq $@   package/lib/lib/64p/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe64Pe package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_init.oe64Pe package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.oe64Pe package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.oe64Pe 
lib/64p/debug/ti.sdo.edma3.drv.ae64Pe: export C_DIR=
lib/64p/debug/ti.sdo.edma3.drv.ae64Pe: PATH:=$(ti.targets.elf.C64P_big_endian.rootDir)/bin/:$(PATH)

clean,e64Pe clean::
	-$(RM) lib/64p/debug/ti.sdo.edma3.drv.ae64Pe
.libraries,e64Pe .libraries: lib/64p/release/ti.sdo.edma3.drv.ae64Pe

-include lib/64p/release/ti.sdo.edma3.drv.ae64Pe.mak
lib/64p/release/ti.sdo.edma3.drv.ae64Pe: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/64p/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe64Pe package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_init.oe64Pe package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_basic.oe64Pe package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_adv.oe64Pe  into $@ ...
	$(ti.targets.elf.C64P_big_endian.rootDir)/bin/ar6x  rq $@   package/lib/lib/64p/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe64Pe package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_init.oe64Pe package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_basic.oe64Pe package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_adv.oe64Pe 
lib/64p/release/ti.sdo.edma3.drv.ae64Pe: export C_DIR=
lib/64p/release/ti.sdo.edma3.drv.ae64Pe: PATH:=$(ti.targets.elf.C64P_big_endian.rootDir)/bin/:$(PATH)

clean,e64Pe clean::
	-$(RM) lib/64p/release/ti.sdo.edma3.drv.ae64Pe
.libraries,e674 .libraries: lib/674/debug/ti.sdo.edma3.drv.ae674

-include lib/674/debug/ti.sdo.edma3.drv.ae674.mak
lib/674/debug/ti.sdo.edma3.drv.ae674: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/674/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe674 package/lib/lib/674/debug/ti.sdo.edma3.drv/src/edma3_drv_init.oe674 package/lib/lib/674/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.oe674 package/lib/lib/674/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.oe674  into $@ ...
	$(ti.targets.elf.C674.rootDir)/bin/ar6x  rq $@   package/lib/lib/674/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe674 package/lib/lib/674/debug/ti.sdo.edma3.drv/src/edma3_drv_init.oe674 package/lib/lib/674/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.oe674 package/lib/lib/674/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.oe674 
lib/674/debug/ti.sdo.edma3.drv.ae674: export C_DIR=
lib/674/debug/ti.sdo.edma3.drv.ae674: PATH:=$(ti.targets.elf.C674.rootDir)/bin/:$(PATH)

clean,e674 clean::
	-$(RM) lib/674/debug/ti.sdo.edma3.drv.ae674
.libraries,e674 .libraries: lib/674/release/ti.sdo.edma3.drv.ae674

-include lib/674/release/ti.sdo.edma3.drv.ae674.mak
lib/674/release/ti.sdo.edma3.drv.ae674: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/674/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe674 package/lib/lib/674/release/ti.sdo.edma3.drv/src/edma3_drv_init.oe674 package/lib/lib/674/release/ti.sdo.edma3.drv/src/edma3_drv_basic.oe674 package/lib/lib/674/release/ti.sdo.edma3.drv/src/edma3_drv_adv.oe674  into $@ ...
	$(ti.targets.elf.C674.rootDir)/bin/ar6x  rq $@   package/lib/lib/674/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe674 package/lib/lib/674/release/ti.sdo.edma3.drv/src/edma3_drv_init.oe674 package/lib/lib/674/release/ti.sdo.edma3.drv/src/edma3_drv_basic.oe674 package/lib/lib/674/release/ti.sdo.edma3.drv/src/edma3_drv_adv.oe674 
lib/674/release/ti.sdo.edma3.drv.ae674: export C_DIR=
lib/674/release/ti.sdo.edma3.drv.ae674: PATH:=$(ti.targets.elf.C674.rootDir)/bin/:$(PATH)

clean,e674 clean::
	-$(RM) lib/674/release/ti.sdo.edma3.drv.ae674
.libraries,e66 .libraries: lib/66/debug/ti.sdo.edma3.drv.ae66

-include lib/66/debug/ti.sdo.edma3.drv.ae66.mak
lib/66/debug/ti.sdo.edma3.drv.ae66: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/66/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe66 package/lib/lib/66/debug/ti.sdo.edma3.drv/src/edma3_drv_init.oe66 package/lib/lib/66/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.oe66 package/lib/lib/66/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.oe66  into $@ ...
	$(ti.targets.elf.C66.rootDir)/bin/ar6x  rq $@   package/lib/lib/66/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe66 package/lib/lib/66/debug/ti.sdo.edma3.drv/src/edma3_drv_init.oe66 package/lib/lib/66/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.oe66 package/lib/lib/66/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.oe66 
lib/66/debug/ti.sdo.edma3.drv.ae66: export C_DIR=
lib/66/debug/ti.sdo.edma3.drv.ae66: PATH:=$(ti.targets.elf.C66.rootDir)/bin/:$(PATH)

clean,e66 clean::
	-$(RM) lib/66/debug/ti.sdo.edma3.drv.ae66
.libraries,e66 .libraries: lib/66/release/ti.sdo.edma3.drv.ae66

-include lib/66/release/ti.sdo.edma3.drv.ae66.mak
lib/66/release/ti.sdo.edma3.drv.ae66: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/66/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe66 package/lib/lib/66/release/ti.sdo.edma3.drv/src/edma3_drv_init.oe66 package/lib/lib/66/release/ti.sdo.edma3.drv/src/edma3_drv_basic.oe66 package/lib/lib/66/release/ti.sdo.edma3.drv/src/edma3_drv_adv.oe66  into $@ ...
	$(ti.targets.elf.C66.rootDir)/bin/ar6x  rq $@   package/lib/lib/66/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe66 package/lib/lib/66/release/ti.sdo.edma3.drv/src/edma3_drv_init.oe66 package/lib/lib/66/release/ti.sdo.edma3.drv/src/edma3_drv_basic.oe66 package/lib/lib/66/release/ti.sdo.edma3.drv/src/edma3_drv_adv.oe66 
lib/66/release/ti.sdo.edma3.drv.ae66: export C_DIR=
lib/66/release/ti.sdo.edma3.drv.ae66: PATH:=$(ti.targets.elf.C66.rootDir)/bin/:$(PATH)

clean,e66 clean::
	-$(RM) lib/66/release/ti.sdo.edma3.drv.ae66
.libraries,e66e .libraries: lib/66/debug/ti.sdo.edma3.drv.ae66e

-include lib/66/debug/ti.sdo.edma3.drv.ae66e.mak
lib/66/debug/ti.sdo.edma3.drv.ae66e: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/66/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe66e package/lib/lib/66/debug/ti.sdo.edma3.drv/src/edma3_drv_init.oe66e package/lib/lib/66/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.oe66e package/lib/lib/66/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.oe66e  into $@ ...
	$(ti.targets.elf.C66_big_endian.rootDir)/bin/ar6x  rq $@   package/lib/lib/66/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe66e package/lib/lib/66/debug/ti.sdo.edma3.drv/src/edma3_drv_init.oe66e package/lib/lib/66/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.oe66e package/lib/lib/66/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.oe66e 
lib/66/debug/ti.sdo.edma3.drv.ae66e: export C_DIR=
lib/66/debug/ti.sdo.edma3.drv.ae66e: PATH:=$(ti.targets.elf.C66_big_endian.rootDir)/bin/:$(PATH)

clean,e66e clean::
	-$(RM) lib/66/debug/ti.sdo.edma3.drv.ae66e
.libraries,e66e .libraries: lib/66/release/ti.sdo.edma3.drv.ae66e

-include lib/66/release/ti.sdo.edma3.drv.ae66e.mak
lib/66/release/ti.sdo.edma3.drv.ae66e: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/66/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe66e package/lib/lib/66/release/ti.sdo.edma3.drv/src/edma3_drv_init.oe66e package/lib/lib/66/release/ti.sdo.edma3.drv/src/edma3_drv_basic.oe66e package/lib/lib/66/release/ti.sdo.edma3.drv/src/edma3_drv_adv.oe66e  into $@ ...
	$(ti.targets.elf.C66_big_endian.rootDir)/bin/ar6x  rq $@   package/lib/lib/66/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe66e package/lib/lib/66/release/ti.sdo.edma3.drv/src/edma3_drv_init.oe66e package/lib/lib/66/release/ti.sdo.edma3.drv/src/edma3_drv_basic.oe66e package/lib/lib/66/release/ti.sdo.edma3.drv/src/edma3_drv_adv.oe66e 
lib/66/release/ti.sdo.edma3.drv.ae66e: export C_DIR=
lib/66/release/ti.sdo.edma3.drv.ae66e: PATH:=$(ti.targets.elf.C66_big_endian.rootDir)/bin/:$(PATH)

clean,e66e clean::
	-$(RM) lib/66/release/ti.sdo.edma3.drv.ae66e
.libraries,e9 .libraries: lib/arm9/debug/ti.sdo.edma3.drv.ae9

-include lib/arm9/debug/ti.sdo.edma3.drv.ae9.mak
lib/arm9/debug/ti.sdo.edma3.drv.ae9: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/arm9/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe9 package/lib/lib/arm9/debug/ti.sdo.edma3.drv/src/edma3_drv_init.oe9 package/lib/lib/arm9/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.oe9 package/lib/lib/arm9/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.oe9  into $@ ...
	$(ti.targets.arm.elf.Arm9.rootDir)/bin/armar  rq $@   package/lib/lib/arm9/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe9 package/lib/lib/arm9/debug/ti.sdo.edma3.drv/src/edma3_drv_init.oe9 package/lib/lib/arm9/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.oe9 package/lib/lib/arm9/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.oe9 
lib/arm9/debug/ti.sdo.edma3.drv.ae9: export C_DIR=
lib/arm9/debug/ti.sdo.edma3.drv.ae9: PATH:=$(ti.targets.arm.elf.Arm9.rootDir)/bin/:$(PATH)

clean,e9 clean::
	-$(RM) lib/arm9/debug/ti.sdo.edma3.drv.ae9
.libraries,e9 .libraries: lib/arm9/release/ti.sdo.edma3.drv.ae9

-include lib/arm9/release/ti.sdo.edma3.drv.ae9.mak
lib/arm9/release/ti.sdo.edma3.drv.ae9: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/arm9/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe9 package/lib/lib/arm9/release/ti.sdo.edma3.drv/src/edma3_drv_init.oe9 package/lib/lib/arm9/release/ti.sdo.edma3.drv/src/edma3_drv_basic.oe9 package/lib/lib/arm9/release/ti.sdo.edma3.drv/src/edma3_drv_adv.oe9  into $@ ...
	$(ti.targets.arm.elf.Arm9.rootDir)/bin/armar  rq $@   package/lib/lib/arm9/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe9 package/lib/lib/arm9/release/ti.sdo.edma3.drv/src/edma3_drv_init.oe9 package/lib/lib/arm9/release/ti.sdo.edma3.drv/src/edma3_drv_basic.oe9 package/lib/lib/arm9/release/ti.sdo.edma3.drv/src/edma3_drv_adv.oe9 
lib/arm9/release/ti.sdo.edma3.drv.ae9: export C_DIR=
lib/arm9/release/ti.sdo.edma3.drv.ae9: PATH:=$(ti.targets.arm.elf.Arm9.rootDir)/bin/:$(PATH)

clean,e9 clean::
	-$(RM) lib/arm9/release/ti.sdo.edma3.drv.ae9
.libraries,ea8f .libraries: lib/a8/debug/ti.sdo.edma3.drv.aea8f

-include lib/a8/debug/ti.sdo.edma3.drv.aea8f.mak
lib/a8/debug/ti.sdo.edma3.drv.aea8f: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/a8/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oea8f package/lib/lib/a8/debug/ti.sdo.edma3.drv/src/edma3_drv_init.oea8f package/lib/lib/a8/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.oea8f package/lib/lib/a8/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.oea8f  into $@ ...
	$(ti.targets.arm.elf.A8F.rootDir)/bin/armar  rq $@   package/lib/lib/a8/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oea8f package/lib/lib/a8/debug/ti.sdo.edma3.drv/src/edma3_drv_init.oea8f package/lib/lib/a8/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.oea8f package/lib/lib/a8/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.oea8f 
lib/a8/debug/ti.sdo.edma3.drv.aea8f: export C_DIR=
lib/a8/debug/ti.sdo.edma3.drv.aea8f: PATH:=$(ti.targets.arm.elf.A8F.rootDir)/bin/:$(PATH)

clean,ea8f clean::
	-$(RM) lib/a8/debug/ti.sdo.edma3.drv.aea8f
.libraries,ea8f .libraries: lib/a8/release/ti.sdo.edma3.drv.aea8f

-include lib/a8/release/ti.sdo.edma3.drv.aea8f.mak
lib/a8/release/ti.sdo.edma3.drv.aea8f: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/a8/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oea8f package/lib/lib/a8/release/ti.sdo.edma3.drv/src/edma3_drv_init.oea8f package/lib/lib/a8/release/ti.sdo.edma3.drv/src/edma3_drv_basic.oea8f package/lib/lib/a8/release/ti.sdo.edma3.drv/src/edma3_drv_adv.oea8f  into $@ ...
	$(ti.targets.arm.elf.A8F.rootDir)/bin/armar  rq $@   package/lib/lib/a8/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oea8f package/lib/lib/a8/release/ti.sdo.edma3.drv/src/edma3_drv_init.oea8f package/lib/lib/a8/release/ti.sdo.edma3.drv/src/edma3_drv_basic.oea8f package/lib/lib/a8/release/ti.sdo.edma3.drv/src/edma3_drv_adv.oea8f 
lib/a8/release/ti.sdo.edma3.drv.aea8f: export C_DIR=
lib/a8/release/ti.sdo.edma3.drv.aea8f: PATH:=$(ti.targets.arm.elf.A8F.rootDir)/bin/:$(PATH)

clean,ea8f clean::
	-$(RM) lib/a8/release/ti.sdo.edma3.drv.aea8f
.libraries,em3 .libraries: lib/m3/debug/ti.sdo.edma3.drv.aem3

-include lib/m3/debug/ti.sdo.edma3.drv.aem3.mak
lib/m3/debug/ti.sdo.edma3.drv.aem3: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/m3/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oem3 package/lib/lib/m3/debug/ti.sdo.edma3.drv/src/edma3_drv_init.oem3 package/lib/lib/m3/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.oem3 package/lib/lib/m3/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.oem3  into $@ ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armar  rq $@   package/lib/lib/m3/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oem3 package/lib/lib/m3/debug/ti.sdo.edma3.drv/src/edma3_drv_init.oem3 package/lib/lib/m3/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.oem3 package/lib/lib/m3/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.oem3 
lib/m3/debug/ti.sdo.edma3.drv.aem3: export C_DIR=
lib/m3/debug/ti.sdo.edma3.drv.aem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

clean,em3 clean::
	-$(RM) lib/m3/debug/ti.sdo.edma3.drv.aem3
.libraries,em3 .libraries: lib/m3/release/ti.sdo.edma3.drv.aem3

-include lib/m3/release/ti.sdo.edma3.drv.aem3.mak
lib/m3/release/ti.sdo.edma3.drv.aem3: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/m3/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oem3 package/lib/lib/m3/release/ti.sdo.edma3.drv/src/edma3_drv_init.oem3 package/lib/lib/m3/release/ti.sdo.edma3.drv/src/edma3_drv_basic.oem3 package/lib/lib/m3/release/ti.sdo.edma3.drv/src/edma3_drv_adv.oem3  into $@ ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armar  rq $@   package/lib/lib/m3/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oem3 package/lib/lib/m3/release/ti.sdo.edma3.drv/src/edma3_drv_init.oem3 package/lib/lib/m3/release/ti.sdo.edma3.drv/src/edma3_drv_basic.oem3 package/lib/lib/m3/release/ti.sdo.edma3.drv/src/edma3_drv_adv.oem3 
lib/m3/release/ti.sdo.edma3.drv.aem3: export C_DIR=
lib/m3/release/ti.sdo.edma3.drv.aem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

clean,em3 clean::
	-$(RM) lib/m3/release/ti.sdo.edma3.drv.aem3
test:;
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
.PHONY: package_ti.sdo.edma3.drv.o64P,copy
package_ti.sdo.edma3.drv.o64P,copy : package_ti.sdo.edma3.drv.o64P,0,copy package_ti.sdo.edma3.drv.o64P,1,copy 
	@

package_ti.sdo.edma3.drv.o64P,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.o64P
package_ti.sdo.edma3.drv.o64P,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.o64P
.PHONY: package_ti.sdo.edma3.drv.s64P,copy
package_ti.sdo.edma3.drv.s64P,copy : package_ti.sdo.edma3.drv.s64P,0,copy package_ti.sdo.edma3.drv.s64P,1,copy 
	@

package_ti.sdo.edma3.drv.s64P,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.s64P
package_ti.sdo.edma3.drv.s64P,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.s64P
.PHONY: edma3_drv_init.o64P,copy
edma3_drv_init.o64P,copy : edma3_drv_init.o64P,0,copy edma3_drv_init.o64P,1,copy 
	@

edma3_drv_init.o64P,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_init.o64P
edma3_drv_init.o64P,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_init.o64P
.PHONY: edma3_drv_init.s64P,copy
edma3_drv_init.s64P,copy : edma3_drv_init.s64P,0,copy edma3_drv_init.s64P,1,copy 
	@

edma3_drv_init.s64P,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_init.s64P
edma3_drv_init.s64P,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_init.s64P
.PHONY: edma3_drv_basic.o64P,copy
edma3_drv_basic.o64P,copy : edma3_drv_basic.o64P,0,copy edma3_drv_basic.o64P,1,copy 
	@

edma3_drv_basic.o64P,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.o64P
edma3_drv_basic.o64P,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_basic.o64P
.PHONY: edma3_drv_basic.s64P,copy
edma3_drv_basic.s64P,copy : edma3_drv_basic.s64P,0,copy edma3_drv_basic.s64P,1,copy 
	@

edma3_drv_basic.s64P,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.s64P
edma3_drv_basic.s64P,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_basic.s64P
.PHONY: edma3_drv_adv.o64P,copy
edma3_drv_adv.o64P,copy : edma3_drv_adv.o64P,0,copy edma3_drv_adv.o64P,1,copy 
	@

edma3_drv_adv.o64P,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.o64P
edma3_drv_adv.o64P,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_adv.o64P
.PHONY: edma3_drv_adv.s64P,copy
edma3_drv_adv.s64P,copy : edma3_drv_adv.s64P,0,copy edma3_drv_adv.s64P,1,copy 
	@

edma3_drv_adv.s64P,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.s64P
edma3_drv_adv.s64P,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_adv.s64P
.PHONY: package_ti.sdo.edma3.drv.o64Pe,copy
package_ti.sdo.edma3.drv.o64Pe,copy : package_ti.sdo.edma3.drv.o64Pe,0,copy package_ti.sdo.edma3.drv.o64Pe,1,copy 
	@

package_ti.sdo.edma3.drv.o64Pe,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.o64Pe
package_ti.sdo.edma3.drv.o64Pe,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.o64Pe
.PHONY: package_ti.sdo.edma3.drv.s64Pe,copy
package_ti.sdo.edma3.drv.s64Pe,copy : package_ti.sdo.edma3.drv.s64Pe,0,copy package_ti.sdo.edma3.drv.s64Pe,1,copy 
	@

package_ti.sdo.edma3.drv.s64Pe,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.s64Pe
package_ti.sdo.edma3.drv.s64Pe,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.s64Pe
.PHONY: edma3_drv_init.o64Pe,copy
edma3_drv_init.o64Pe,copy : edma3_drv_init.o64Pe,0,copy edma3_drv_init.o64Pe,1,copy 
	@

edma3_drv_init.o64Pe,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_init.o64Pe
edma3_drv_init.o64Pe,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_init.o64Pe
.PHONY: edma3_drv_init.s64Pe,copy
edma3_drv_init.s64Pe,copy : edma3_drv_init.s64Pe,0,copy edma3_drv_init.s64Pe,1,copy 
	@

edma3_drv_init.s64Pe,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_init.s64Pe
edma3_drv_init.s64Pe,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_init.s64Pe
.PHONY: edma3_drv_basic.o64Pe,copy
edma3_drv_basic.o64Pe,copy : edma3_drv_basic.o64Pe,0,copy edma3_drv_basic.o64Pe,1,copy 
	@

edma3_drv_basic.o64Pe,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.o64Pe
edma3_drv_basic.o64Pe,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_basic.o64Pe
.PHONY: edma3_drv_basic.s64Pe,copy
edma3_drv_basic.s64Pe,copy : edma3_drv_basic.s64Pe,0,copy edma3_drv_basic.s64Pe,1,copy 
	@

edma3_drv_basic.s64Pe,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.s64Pe
edma3_drv_basic.s64Pe,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_basic.s64Pe
.PHONY: edma3_drv_adv.o64Pe,copy
edma3_drv_adv.o64Pe,copy : edma3_drv_adv.o64Pe,0,copy edma3_drv_adv.o64Pe,1,copy 
	@

edma3_drv_adv.o64Pe,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.o64Pe
edma3_drv_adv.o64Pe,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_adv.o64Pe
.PHONY: edma3_drv_adv.s64Pe,copy
edma3_drv_adv.s64Pe,copy : edma3_drv_adv.s64Pe,0,copy edma3_drv_adv.s64Pe,1,copy 
	@

edma3_drv_adv.s64Pe,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.s64Pe
edma3_drv_adv.s64Pe,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_adv.s64Pe
.PHONY: package_ti.sdo.edma3.drv.o674,copy
package_ti.sdo.edma3.drv.o674,copy : package_ti.sdo.edma3.drv.o674,0,copy package_ti.sdo.edma3.drv.o674,1,copy 
	@

package_ti.sdo.edma3.drv.o674,0,copy : package/lib/lib/674/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.o674
package_ti.sdo.edma3.drv.o674,1,copy : package/lib/lib/674/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.o674
.PHONY: package_ti.sdo.edma3.drv.s674,copy
package_ti.sdo.edma3.drv.s674,copy : package_ti.sdo.edma3.drv.s674,0,copy package_ti.sdo.edma3.drv.s674,1,copy 
	@

package_ti.sdo.edma3.drv.s674,0,copy : package/lib/lib/674/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.s674
package_ti.sdo.edma3.drv.s674,1,copy : package/lib/lib/674/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.s674
.PHONY: edma3_drv_init.o674,copy
edma3_drv_init.o674,copy : edma3_drv_init.o674,0,copy edma3_drv_init.o674,1,copy 
	@

edma3_drv_init.o674,0,copy : package/lib/lib/674/debug/ti.sdo.edma3.drv/src/edma3_drv_init.o674
edma3_drv_init.o674,1,copy : package/lib/lib/674/release/ti.sdo.edma3.drv/src/edma3_drv_init.o674
.PHONY: edma3_drv_init.s674,copy
edma3_drv_init.s674,copy : edma3_drv_init.s674,0,copy edma3_drv_init.s674,1,copy 
	@

edma3_drv_init.s674,0,copy : package/lib/lib/674/debug/ti.sdo.edma3.drv/src/edma3_drv_init.s674
edma3_drv_init.s674,1,copy : package/lib/lib/674/release/ti.sdo.edma3.drv/src/edma3_drv_init.s674
.PHONY: edma3_drv_basic.o674,copy
edma3_drv_basic.o674,copy : edma3_drv_basic.o674,0,copy edma3_drv_basic.o674,1,copy 
	@

edma3_drv_basic.o674,0,copy : package/lib/lib/674/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.o674
edma3_drv_basic.o674,1,copy : package/lib/lib/674/release/ti.sdo.edma3.drv/src/edma3_drv_basic.o674
.PHONY: edma3_drv_basic.s674,copy
edma3_drv_basic.s674,copy : edma3_drv_basic.s674,0,copy edma3_drv_basic.s674,1,copy 
	@

edma3_drv_basic.s674,0,copy : package/lib/lib/674/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.s674
edma3_drv_basic.s674,1,copy : package/lib/lib/674/release/ti.sdo.edma3.drv/src/edma3_drv_basic.s674
.PHONY: edma3_drv_adv.o674,copy
edma3_drv_adv.o674,copy : edma3_drv_adv.o674,0,copy edma3_drv_adv.o674,1,copy 
	@

edma3_drv_adv.o674,0,copy : package/lib/lib/674/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.o674
edma3_drv_adv.o674,1,copy : package/lib/lib/674/release/ti.sdo.edma3.drv/src/edma3_drv_adv.o674
.PHONY: edma3_drv_adv.s674,copy
edma3_drv_adv.s674,copy : edma3_drv_adv.s674,0,copy edma3_drv_adv.s674,1,copy 
	@

edma3_drv_adv.s674,0,copy : package/lib/lib/674/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.s674
edma3_drv_adv.s674,1,copy : package/lib/lib/674/release/ti.sdo.edma3.drv/src/edma3_drv_adv.s674
.PHONY: package_ti.sdo.edma3.drv.oe64P,copy
package_ti.sdo.edma3.drv.oe64P,copy : package_ti.sdo.edma3.drv.oe64P,0,copy package_ti.sdo.edma3.drv.oe64P,1,copy 
	@

package_ti.sdo.edma3.drv.oe64P,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe64P
package_ti.sdo.edma3.drv.oe64P,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe64P
.PHONY: package_ti.sdo.edma3.drv.se64P,copy
package_ti.sdo.edma3.drv.se64P,copy : package_ti.sdo.edma3.drv.se64P,0,copy package_ti.sdo.edma3.drv.se64P,1,copy 
	@

package_ti.sdo.edma3.drv.se64P,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.se64P
package_ti.sdo.edma3.drv.se64P,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.se64P
.PHONY: edma3_drv_init.oe64P,copy
edma3_drv_init.oe64P,copy : edma3_drv_init.oe64P,0,copy edma3_drv_init.oe64P,1,copy 
	@

edma3_drv_init.oe64P,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_init.oe64P
edma3_drv_init.oe64P,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_init.oe64P
.PHONY: edma3_drv_init.se64P,copy
edma3_drv_init.se64P,copy : edma3_drv_init.se64P,0,copy edma3_drv_init.se64P,1,copy 
	@

edma3_drv_init.se64P,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_init.se64P
edma3_drv_init.se64P,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_init.se64P
.PHONY: edma3_drv_basic.oe64P,copy
edma3_drv_basic.oe64P,copy : edma3_drv_basic.oe64P,0,copy edma3_drv_basic.oe64P,1,copy 
	@

edma3_drv_basic.oe64P,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.oe64P
edma3_drv_basic.oe64P,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_basic.oe64P
.PHONY: edma3_drv_basic.se64P,copy
edma3_drv_basic.se64P,copy : edma3_drv_basic.se64P,0,copy edma3_drv_basic.se64P,1,copy 
	@

edma3_drv_basic.se64P,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.se64P
edma3_drv_basic.se64P,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_basic.se64P
.PHONY: edma3_drv_adv.oe64P,copy
edma3_drv_adv.oe64P,copy : edma3_drv_adv.oe64P,0,copy edma3_drv_adv.oe64P,1,copy 
	@

edma3_drv_adv.oe64P,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.oe64P
edma3_drv_adv.oe64P,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_adv.oe64P
.PHONY: edma3_drv_adv.se64P,copy
edma3_drv_adv.se64P,copy : edma3_drv_adv.se64P,0,copy edma3_drv_adv.se64P,1,copy 
	@

edma3_drv_adv.se64P,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.se64P
edma3_drv_adv.se64P,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_adv.se64P
.PHONY: package_ti.sdo.edma3.drv.oe64Pe,copy
package_ti.sdo.edma3.drv.oe64Pe,copy : package_ti.sdo.edma3.drv.oe64Pe,0,copy package_ti.sdo.edma3.drv.oe64Pe,1,copy 
	@

package_ti.sdo.edma3.drv.oe64Pe,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe64Pe
package_ti.sdo.edma3.drv.oe64Pe,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe64Pe
.PHONY: package_ti.sdo.edma3.drv.se64Pe,copy
package_ti.sdo.edma3.drv.se64Pe,copy : package_ti.sdo.edma3.drv.se64Pe,0,copy package_ti.sdo.edma3.drv.se64Pe,1,copy 
	@

package_ti.sdo.edma3.drv.se64Pe,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.se64Pe
package_ti.sdo.edma3.drv.se64Pe,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.se64Pe
.PHONY: edma3_drv_init.oe64Pe,copy
edma3_drv_init.oe64Pe,copy : edma3_drv_init.oe64Pe,0,copy edma3_drv_init.oe64Pe,1,copy 
	@

edma3_drv_init.oe64Pe,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_init.oe64Pe
edma3_drv_init.oe64Pe,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_init.oe64Pe
.PHONY: edma3_drv_init.se64Pe,copy
edma3_drv_init.se64Pe,copy : edma3_drv_init.se64Pe,0,copy edma3_drv_init.se64Pe,1,copy 
	@

edma3_drv_init.se64Pe,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_init.se64Pe
edma3_drv_init.se64Pe,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_init.se64Pe
.PHONY: edma3_drv_basic.oe64Pe,copy
edma3_drv_basic.oe64Pe,copy : edma3_drv_basic.oe64Pe,0,copy edma3_drv_basic.oe64Pe,1,copy 
	@

edma3_drv_basic.oe64Pe,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.oe64Pe
edma3_drv_basic.oe64Pe,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_basic.oe64Pe
.PHONY: edma3_drv_basic.se64Pe,copy
edma3_drv_basic.se64Pe,copy : edma3_drv_basic.se64Pe,0,copy edma3_drv_basic.se64Pe,1,copy 
	@

edma3_drv_basic.se64Pe,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.se64Pe
edma3_drv_basic.se64Pe,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_basic.se64Pe
.PHONY: edma3_drv_adv.oe64Pe,copy
edma3_drv_adv.oe64Pe,copy : edma3_drv_adv.oe64Pe,0,copy edma3_drv_adv.oe64Pe,1,copy 
	@

edma3_drv_adv.oe64Pe,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.oe64Pe
edma3_drv_adv.oe64Pe,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_adv.oe64Pe
.PHONY: edma3_drv_adv.se64Pe,copy
edma3_drv_adv.se64Pe,copy : edma3_drv_adv.se64Pe,0,copy edma3_drv_adv.se64Pe,1,copy 
	@

edma3_drv_adv.se64Pe,0,copy : package/lib/lib/64p/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.se64Pe
edma3_drv_adv.se64Pe,1,copy : package/lib/lib/64p/release/ti.sdo.edma3.drv/src/edma3_drv_adv.se64Pe
.PHONY: package_ti.sdo.edma3.drv.oe674,copy
package_ti.sdo.edma3.drv.oe674,copy : package_ti.sdo.edma3.drv.oe674,0,copy package_ti.sdo.edma3.drv.oe674,1,copy 
	@

package_ti.sdo.edma3.drv.oe674,0,copy : package/lib/lib/674/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe674
package_ti.sdo.edma3.drv.oe674,1,copy : package/lib/lib/674/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe674
.PHONY: package_ti.sdo.edma3.drv.se674,copy
package_ti.sdo.edma3.drv.se674,copy : package_ti.sdo.edma3.drv.se674,0,copy package_ti.sdo.edma3.drv.se674,1,copy 
	@

package_ti.sdo.edma3.drv.se674,0,copy : package/lib/lib/674/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.se674
package_ti.sdo.edma3.drv.se674,1,copy : package/lib/lib/674/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.se674
.PHONY: edma3_drv_init.oe674,copy
edma3_drv_init.oe674,copy : edma3_drv_init.oe674,0,copy edma3_drv_init.oe674,1,copy 
	@

edma3_drv_init.oe674,0,copy : package/lib/lib/674/debug/ti.sdo.edma3.drv/src/edma3_drv_init.oe674
edma3_drv_init.oe674,1,copy : package/lib/lib/674/release/ti.sdo.edma3.drv/src/edma3_drv_init.oe674
.PHONY: edma3_drv_init.se674,copy
edma3_drv_init.se674,copy : edma3_drv_init.se674,0,copy edma3_drv_init.se674,1,copy 
	@

edma3_drv_init.se674,0,copy : package/lib/lib/674/debug/ti.sdo.edma3.drv/src/edma3_drv_init.se674
edma3_drv_init.se674,1,copy : package/lib/lib/674/release/ti.sdo.edma3.drv/src/edma3_drv_init.se674
.PHONY: edma3_drv_basic.oe674,copy
edma3_drv_basic.oe674,copy : edma3_drv_basic.oe674,0,copy edma3_drv_basic.oe674,1,copy 
	@

edma3_drv_basic.oe674,0,copy : package/lib/lib/674/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.oe674
edma3_drv_basic.oe674,1,copy : package/lib/lib/674/release/ti.sdo.edma3.drv/src/edma3_drv_basic.oe674
.PHONY: edma3_drv_basic.se674,copy
edma3_drv_basic.se674,copy : edma3_drv_basic.se674,0,copy edma3_drv_basic.se674,1,copy 
	@

edma3_drv_basic.se674,0,copy : package/lib/lib/674/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.se674
edma3_drv_basic.se674,1,copy : package/lib/lib/674/release/ti.sdo.edma3.drv/src/edma3_drv_basic.se674
.PHONY: edma3_drv_adv.oe674,copy
edma3_drv_adv.oe674,copy : edma3_drv_adv.oe674,0,copy edma3_drv_adv.oe674,1,copy 
	@

edma3_drv_adv.oe674,0,copy : package/lib/lib/674/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.oe674
edma3_drv_adv.oe674,1,copy : package/lib/lib/674/release/ti.sdo.edma3.drv/src/edma3_drv_adv.oe674
.PHONY: edma3_drv_adv.se674,copy
edma3_drv_adv.se674,copy : edma3_drv_adv.se674,0,copy edma3_drv_adv.se674,1,copy 
	@

edma3_drv_adv.se674,0,copy : package/lib/lib/674/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.se674
edma3_drv_adv.se674,1,copy : package/lib/lib/674/release/ti.sdo.edma3.drv/src/edma3_drv_adv.se674
.PHONY: package_ti.sdo.edma3.drv.oe66,copy
package_ti.sdo.edma3.drv.oe66,copy : package_ti.sdo.edma3.drv.oe66,0,copy package_ti.sdo.edma3.drv.oe66,1,copy 
	@

package_ti.sdo.edma3.drv.oe66,0,copy : package/lib/lib/66/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe66
package_ti.sdo.edma3.drv.oe66,1,copy : package/lib/lib/66/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe66
.PHONY: package_ti.sdo.edma3.drv.se66,copy
package_ti.sdo.edma3.drv.se66,copy : package_ti.sdo.edma3.drv.se66,0,copy package_ti.sdo.edma3.drv.se66,1,copy 
	@

package_ti.sdo.edma3.drv.se66,0,copy : package/lib/lib/66/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.se66
package_ti.sdo.edma3.drv.se66,1,copy : package/lib/lib/66/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.se66
.PHONY: edma3_drv_init.oe66,copy
edma3_drv_init.oe66,copy : edma3_drv_init.oe66,0,copy edma3_drv_init.oe66,1,copy 
	@

edma3_drv_init.oe66,0,copy : package/lib/lib/66/debug/ti.sdo.edma3.drv/src/edma3_drv_init.oe66
edma3_drv_init.oe66,1,copy : package/lib/lib/66/release/ti.sdo.edma3.drv/src/edma3_drv_init.oe66
.PHONY: edma3_drv_init.se66,copy
edma3_drv_init.se66,copy : edma3_drv_init.se66,0,copy edma3_drv_init.se66,1,copy 
	@

edma3_drv_init.se66,0,copy : package/lib/lib/66/debug/ti.sdo.edma3.drv/src/edma3_drv_init.se66
edma3_drv_init.se66,1,copy : package/lib/lib/66/release/ti.sdo.edma3.drv/src/edma3_drv_init.se66
.PHONY: edma3_drv_basic.oe66,copy
edma3_drv_basic.oe66,copy : edma3_drv_basic.oe66,0,copy edma3_drv_basic.oe66,1,copy 
	@

edma3_drv_basic.oe66,0,copy : package/lib/lib/66/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.oe66
edma3_drv_basic.oe66,1,copy : package/lib/lib/66/release/ti.sdo.edma3.drv/src/edma3_drv_basic.oe66
.PHONY: edma3_drv_basic.se66,copy
edma3_drv_basic.se66,copy : edma3_drv_basic.se66,0,copy edma3_drv_basic.se66,1,copy 
	@

edma3_drv_basic.se66,0,copy : package/lib/lib/66/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.se66
edma3_drv_basic.se66,1,copy : package/lib/lib/66/release/ti.sdo.edma3.drv/src/edma3_drv_basic.se66
.PHONY: edma3_drv_adv.oe66,copy
edma3_drv_adv.oe66,copy : edma3_drv_adv.oe66,0,copy edma3_drv_adv.oe66,1,copy 
	@

edma3_drv_adv.oe66,0,copy : package/lib/lib/66/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.oe66
edma3_drv_adv.oe66,1,copy : package/lib/lib/66/release/ti.sdo.edma3.drv/src/edma3_drv_adv.oe66
.PHONY: edma3_drv_adv.se66,copy
edma3_drv_adv.se66,copy : edma3_drv_adv.se66,0,copy edma3_drv_adv.se66,1,copy 
	@

edma3_drv_adv.se66,0,copy : package/lib/lib/66/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.se66
edma3_drv_adv.se66,1,copy : package/lib/lib/66/release/ti.sdo.edma3.drv/src/edma3_drv_adv.se66
.PHONY: package_ti.sdo.edma3.drv.oe66e,copy
package_ti.sdo.edma3.drv.oe66e,copy : package_ti.sdo.edma3.drv.oe66e,0,copy package_ti.sdo.edma3.drv.oe66e,1,copy 
	@

package_ti.sdo.edma3.drv.oe66e,0,copy : package/lib/lib/66/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe66e
package_ti.sdo.edma3.drv.oe66e,1,copy : package/lib/lib/66/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe66e
.PHONY: package_ti.sdo.edma3.drv.se66e,copy
package_ti.sdo.edma3.drv.se66e,copy : package_ti.sdo.edma3.drv.se66e,0,copy package_ti.sdo.edma3.drv.se66e,1,copy 
	@

package_ti.sdo.edma3.drv.se66e,0,copy : package/lib/lib/66/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.se66e
package_ti.sdo.edma3.drv.se66e,1,copy : package/lib/lib/66/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.se66e
.PHONY: edma3_drv_init.oe66e,copy
edma3_drv_init.oe66e,copy : edma3_drv_init.oe66e,0,copy edma3_drv_init.oe66e,1,copy 
	@

edma3_drv_init.oe66e,0,copy : package/lib/lib/66/debug/ti.sdo.edma3.drv/src/edma3_drv_init.oe66e
edma3_drv_init.oe66e,1,copy : package/lib/lib/66/release/ti.sdo.edma3.drv/src/edma3_drv_init.oe66e
.PHONY: edma3_drv_init.se66e,copy
edma3_drv_init.se66e,copy : edma3_drv_init.se66e,0,copy edma3_drv_init.se66e,1,copy 
	@

edma3_drv_init.se66e,0,copy : package/lib/lib/66/debug/ti.sdo.edma3.drv/src/edma3_drv_init.se66e
edma3_drv_init.se66e,1,copy : package/lib/lib/66/release/ti.sdo.edma3.drv/src/edma3_drv_init.se66e
.PHONY: edma3_drv_basic.oe66e,copy
edma3_drv_basic.oe66e,copy : edma3_drv_basic.oe66e,0,copy edma3_drv_basic.oe66e,1,copy 
	@

edma3_drv_basic.oe66e,0,copy : package/lib/lib/66/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.oe66e
edma3_drv_basic.oe66e,1,copy : package/lib/lib/66/release/ti.sdo.edma3.drv/src/edma3_drv_basic.oe66e
.PHONY: edma3_drv_basic.se66e,copy
edma3_drv_basic.se66e,copy : edma3_drv_basic.se66e,0,copy edma3_drv_basic.se66e,1,copy 
	@

edma3_drv_basic.se66e,0,copy : package/lib/lib/66/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.se66e
edma3_drv_basic.se66e,1,copy : package/lib/lib/66/release/ti.sdo.edma3.drv/src/edma3_drv_basic.se66e
.PHONY: edma3_drv_adv.oe66e,copy
edma3_drv_adv.oe66e,copy : edma3_drv_adv.oe66e,0,copy edma3_drv_adv.oe66e,1,copy 
	@

edma3_drv_adv.oe66e,0,copy : package/lib/lib/66/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.oe66e
edma3_drv_adv.oe66e,1,copy : package/lib/lib/66/release/ti.sdo.edma3.drv/src/edma3_drv_adv.oe66e
.PHONY: edma3_drv_adv.se66e,copy
edma3_drv_adv.se66e,copy : edma3_drv_adv.se66e,0,copy edma3_drv_adv.se66e,1,copy 
	@

edma3_drv_adv.se66e,0,copy : package/lib/lib/66/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.se66e
edma3_drv_adv.se66e,1,copy : package/lib/lib/66/release/ti.sdo.edma3.drv/src/edma3_drv_adv.se66e
.PHONY: package_ti.sdo.edma3.drv.oe9,copy
package_ti.sdo.edma3.drv.oe9,copy : package_ti.sdo.edma3.drv.oe9,0,copy package_ti.sdo.edma3.drv.oe9,1,copy 
	@

package_ti.sdo.edma3.drv.oe9,0,copy : package/lib/lib/arm9/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe9
package_ti.sdo.edma3.drv.oe9,1,copy : package/lib/lib/arm9/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oe9
.PHONY: package_ti.sdo.edma3.drv.se9,copy
package_ti.sdo.edma3.drv.se9,copy : package_ti.sdo.edma3.drv.se9,0,copy package_ti.sdo.edma3.drv.se9,1,copy 
	@

package_ti.sdo.edma3.drv.se9,0,copy : package/lib/lib/arm9/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.se9
package_ti.sdo.edma3.drv.se9,1,copy : package/lib/lib/arm9/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.se9
.PHONY: edma3_drv_init.oe9,copy
edma3_drv_init.oe9,copy : edma3_drv_init.oe9,0,copy edma3_drv_init.oe9,1,copy 
	@

edma3_drv_init.oe9,0,copy : package/lib/lib/arm9/debug/ti.sdo.edma3.drv/src/edma3_drv_init.oe9
edma3_drv_init.oe9,1,copy : package/lib/lib/arm9/release/ti.sdo.edma3.drv/src/edma3_drv_init.oe9
.PHONY: edma3_drv_init.se9,copy
edma3_drv_init.se9,copy : edma3_drv_init.se9,0,copy edma3_drv_init.se9,1,copy 
	@

edma3_drv_init.se9,0,copy : package/lib/lib/arm9/debug/ti.sdo.edma3.drv/src/edma3_drv_init.se9
edma3_drv_init.se9,1,copy : package/lib/lib/arm9/release/ti.sdo.edma3.drv/src/edma3_drv_init.se9
.PHONY: edma3_drv_basic.oe9,copy
edma3_drv_basic.oe9,copy : edma3_drv_basic.oe9,0,copy edma3_drv_basic.oe9,1,copy 
	@

edma3_drv_basic.oe9,0,copy : package/lib/lib/arm9/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.oe9
edma3_drv_basic.oe9,1,copy : package/lib/lib/arm9/release/ti.sdo.edma3.drv/src/edma3_drv_basic.oe9
.PHONY: edma3_drv_basic.se9,copy
edma3_drv_basic.se9,copy : edma3_drv_basic.se9,0,copy edma3_drv_basic.se9,1,copy 
	@

edma3_drv_basic.se9,0,copy : package/lib/lib/arm9/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.se9
edma3_drv_basic.se9,1,copy : package/lib/lib/arm9/release/ti.sdo.edma3.drv/src/edma3_drv_basic.se9
.PHONY: edma3_drv_adv.oe9,copy
edma3_drv_adv.oe9,copy : edma3_drv_adv.oe9,0,copy edma3_drv_adv.oe9,1,copy 
	@

edma3_drv_adv.oe9,0,copy : package/lib/lib/arm9/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.oe9
edma3_drv_adv.oe9,1,copy : package/lib/lib/arm9/release/ti.sdo.edma3.drv/src/edma3_drv_adv.oe9
.PHONY: edma3_drv_adv.se9,copy
edma3_drv_adv.se9,copy : edma3_drv_adv.se9,0,copy edma3_drv_adv.se9,1,copy 
	@

edma3_drv_adv.se9,0,copy : package/lib/lib/arm9/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.se9
edma3_drv_adv.se9,1,copy : package/lib/lib/arm9/release/ti.sdo.edma3.drv/src/edma3_drv_adv.se9
.PHONY: package_ti.sdo.edma3.drv.oea8f,copy
package_ti.sdo.edma3.drv.oea8f,copy : package_ti.sdo.edma3.drv.oea8f,0,copy package_ti.sdo.edma3.drv.oea8f,1,copy 
	@

package_ti.sdo.edma3.drv.oea8f,0,copy : package/lib/lib/a8/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oea8f
package_ti.sdo.edma3.drv.oea8f,1,copy : package/lib/lib/a8/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oea8f
.PHONY: package_ti.sdo.edma3.drv.sea8f,copy
package_ti.sdo.edma3.drv.sea8f,copy : package_ti.sdo.edma3.drv.sea8f,0,copy package_ti.sdo.edma3.drv.sea8f,1,copy 
	@

package_ti.sdo.edma3.drv.sea8f,0,copy : package/lib/lib/a8/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.sea8f
package_ti.sdo.edma3.drv.sea8f,1,copy : package/lib/lib/a8/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.sea8f
.PHONY: edma3_drv_init.oea8f,copy
edma3_drv_init.oea8f,copy : edma3_drv_init.oea8f,0,copy edma3_drv_init.oea8f,1,copy 
	@

edma3_drv_init.oea8f,0,copy : package/lib/lib/a8/debug/ti.sdo.edma3.drv/src/edma3_drv_init.oea8f
edma3_drv_init.oea8f,1,copy : package/lib/lib/a8/release/ti.sdo.edma3.drv/src/edma3_drv_init.oea8f
.PHONY: edma3_drv_init.sea8f,copy
edma3_drv_init.sea8f,copy : edma3_drv_init.sea8f,0,copy edma3_drv_init.sea8f,1,copy 
	@

edma3_drv_init.sea8f,0,copy : package/lib/lib/a8/debug/ti.sdo.edma3.drv/src/edma3_drv_init.sea8f
edma3_drv_init.sea8f,1,copy : package/lib/lib/a8/release/ti.sdo.edma3.drv/src/edma3_drv_init.sea8f
.PHONY: edma3_drv_basic.oea8f,copy
edma3_drv_basic.oea8f,copy : edma3_drv_basic.oea8f,0,copy edma3_drv_basic.oea8f,1,copy 
	@

edma3_drv_basic.oea8f,0,copy : package/lib/lib/a8/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.oea8f
edma3_drv_basic.oea8f,1,copy : package/lib/lib/a8/release/ti.sdo.edma3.drv/src/edma3_drv_basic.oea8f
.PHONY: edma3_drv_basic.sea8f,copy
edma3_drv_basic.sea8f,copy : edma3_drv_basic.sea8f,0,copy edma3_drv_basic.sea8f,1,copy 
	@

edma3_drv_basic.sea8f,0,copy : package/lib/lib/a8/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.sea8f
edma3_drv_basic.sea8f,1,copy : package/lib/lib/a8/release/ti.sdo.edma3.drv/src/edma3_drv_basic.sea8f
.PHONY: edma3_drv_adv.oea8f,copy
edma3_drv_adv.oea8f,copy : edma3_drv_adv.oea8f,0,copy edma3_drv_adv.oea8f,1,copy 
	@

edma3_drv_adv.oea8f,0,copy : package/lib/lib/a8/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.oea8f
edma3_drv_adv.oea8f,1,copy : package/lib/lib/a8/release/ti.sdo.edma3.drv/src/edma3_drv_adv.oea8f
.PHONY: edma3_drv_adv.sea8f,copy
edma3_drv_adv.sea8f,copy : edma3_drv_adv.sea8f,0,copy edma3_drv_adv.sea8f,1,copy 
	@

edma3_drv_adv.sea8f,0,copy : package/lib/lib/a8/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.sea8f
edma3_drv_adv.sea8f,1,copy : package/lib/lib/a8/release/ti.sdo.edma3.drv/src/edma3_drv_adv.sea8f
.PHONY: package_ti.sdo.edma3.drv.oem3,copy
package_ti.sdo.edma3.drv.oem3,copy : package_ti.sdo.edma3.drv.oem3,0,copy package_ti.sdo.edma3.drv.oem3,1,copy 
	@

package_ti.sdo.edma3.drv.oem3,0,copy : package/lib/lib/m3/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oem3
package_ti.sdo.edma3.drv.oem3,1,copy : package/lib/lib/m3/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.oem3
.PHONY: package_ti.sdo.edma3.drv.sem3,copy
package_ti.sdo.edma3.drv.sem3,copy : package_ti.sdo.edma3.drv.sem3,0,copy package_ti.sdo.edma3.drv.sem3,1,copy 
	@

package_ti.sdo.edma3.drv.sem3,0,copy : package/lib/lib/m3/debug/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.sem3
package_ti.sdo.edma3.drv.sem3,1,copy : package/lib/lib/m3/release/ti.sdo.edma3.drv/package/package_ti.sdo.edma3.drv.sem3
.PHONY: edma3_drv_init.oem3,copy
edma3_drv_init.oem3,copy : edma3_drv_init.oem3,0,copy edma3_drv_init.oem3,1,copy 
	@

edma3_drv_init.oem3,0,copy : package/lib/lib/m3/debug/ti.sdo.edma3.drv/src/edma3_drv_init.oem3
edma3_drv_init.oem3,1,copy : package/lib/lib/m3/release/ti.sdo.edma3.drv/src/edma3_drv_init.oem3
.PHONY: edma3_drv_init.sem3,copy
edma3_drv_init.sem3,copy : edma3_drv_init.sem3,0,copy edma3_drv_init.sem3,1,copy 
	@

edma3_drv_init.sem3,0,copy : package/lib/lib/m3/debug/ti.sdo.edma3.drv/src/edma3_drv_init.sem3
edma3_drv_init.sem3,1,copy : package/lib/lib/m3/release/ti.sdo.edma3.drv/src/edma3_drv_init.sem3
.PHONY: edma3_drv_basic.oem3,copy
edma3_drv_basic.oem3,copy : edma3_drv_basic.oem3,0,copy edma3_drv_basic.oem3,1,copy 
	@

edma3_drv_basic.oem3,0,copy : package/lib/lib/m3/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.oem3
edma3_drv_basic.oem3,1,copy : package/lib/lib/m3/release/ti.sdo.edma3.drv/src/edma3_drv_basic.oem3
.PHONY: edma3_drv_basic.sem3,copy
edma3_drv_basic.sem3,copy : edma3_drv_basic.sem3,0,copy edma3_drv_basic.sem3,1,copy 
	@

edma3_drv_basic.sem3,0,copy : package/lib/lib/m3/debug/ti.sdo.edma3.drv/src/edma3_drv_basic.sem3
edma3_drv_basic.sem3,1,copy : package/lib/lib/m3/release/ti.sdo.edma3.drv/src/edma3_drv_basic.sem3
.PHONY: edma3_drv_adv.oem3,copy
edma3_drv_adv.oem3,copy : edma3_drv_adv.oem3,0,copy edma3_drv_adv.oem3,1,copy 
	@

edma3_drv_adv.oem3,0,copy : package/lib/lib/m3/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.oem3
edma3_drv_adv.oem3,1,copy : package/lib/lib/m3/release/ti.sdo.edma3.drv/src/edma3_drv_adv.oem3
.PHONY: edma3_drv_adv.sem3,copy
edma3_drv_adv.sem3,copy : edma3_drv_adv.sem3,0,copy edma3_drv_adv.sem3,1,copy 
	@

edma3_drv_adv.sem3,0,copy : package/lib/lib/m3/debug/ti.sdo.edma3.drv/src/edma3_drv_adv.sem3
edma3_drv_adv.sem3,1,copy : package/lib/lib/m3/release/ti.sdo.edma3.drv/src/edma3_drv_adv.sem3

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg $(XDCROOT)/packages/xdc/cfg/Main.xs | .interfaces
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,ti_sdo_edma3_drv
ifeq (,$(MK_NOGENDEPS))
-include package/rel/ti_sdo_edma3_drv.tar.dep
endif
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: package/package.bld.xml
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: package/build.cfg
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: package/package.xdc.inc
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: .settings/org.eclipse.cdt.core.prefs
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: docs
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/debug/ti.sdo.edma3.drv.a64P
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/debug/ti.sdo.edma3.drv.a64Pe
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/debug/ti.sdo.edma3.drv.a674
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/release/ti.sdo.edma3.drv.a64P
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/release/ti.sdo.edma3.drv.a64Pe
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/release/ti.sdo.edma3.drv.a674
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/debug/ti.sdo.edma3.drv.ae64P
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/debug/ti.sdo.edma3.drv.ae64Pe
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/debug/ti.sdo.edma3.drv.ae674
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/release/ti.sdo.edma3.drv.ae64P
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/release/ti.sdo.edma3.drv.ae64Pe
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/release/ti.sdo.edma3.drv.ae674
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/debug/ti.sdo.edma3.drv.ae66
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/debug/ti.sdo.edma3.drv.ae66e
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/release/ti.sdo.edma3.drv.ae66
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/release/ti.sdo.edma3.drv.ae66e
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/release/ti.sdo.edma3.drv.a64P_size.txt
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/release/ti.sdo.edma3.drv.a64Pe_size.txt
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/release/ti.sdo.edma3.drv.ae64P_size.txt
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/release/ti.sdo.edma3.drv.ae64Pe_size.txt
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/release/ti.sdo.edma3.drv.ae66_size.txt
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/release/ti.sdo.edma3.drv.ae66e_size.txt
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: src
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: .cdtproject
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: .project
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: DRV.xdc
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: edma3_drv.h
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: package.bld
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: package.xs
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: package/package.cfg.xdc.inc
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/64p/debug/ti.sdo.edma3.drv.a64P
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/64p/release/ti.sdo.edma3.drv.a64P
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/64p/debug/ti.sdo.edma3.drv.a64Pe
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/64p/release/ti.sdo.edma3.drv.a64Pe
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/674/debug/ti.sdo.edma3.drv.a674
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/674/release/ti.sdo.edma3.drv.a674
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/64p/debug/ti.sdo.edma3.drv.ae64P
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/64p/release/ti.sdo.edma3.drv.ae64P
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/64p/debug/ti.sdo.edma3.drv.ae64Pe
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/64p/release/ti.sdo.edma3.drv.ae64Pe
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/674/debug/ti.sdo.edma3.drv.ae674
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/674/release/ti.sdo.edma3.drv.ae674
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/66/debug/ti.sdo.edma3.drv.ae66
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/66/release/ti.sdo.edma3.drv.ae66
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/66/debug/ti.sdo.edma3.drv.ae66e
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/66/release/ti.sdo.edma3.drv.ae66e
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/arm9/debug/ti.sdo.edma3.drv.ae9
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/arm9/release/ti.sdo.edma3.drv.ae9
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/a8/debug/ti.sdo.edma3.drv.aea8f
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/a8/release/ti.sdo.edma3.drv.aea8f
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/m3/debug/ti.sdo.edma3.drv.aem3
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: lib/m3/release/ti.sdo.edma3.drv.aem3
package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml: .force
	@$(MSG) generating external release references $@ ...
	$(XS) $(JSENV) -f $(XDCROOT)/packages/xdc/bld/rel.js $(MK_RELOPTS) . $@

ti_sdo_edma3_drv.tar: package/rel/ti_sdo_edma3_drv.xdc.inc package/rel/ti_sdo_edma3_drv/ti/sdo/edma3/drv/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/ti_sdo_edma3_drv.xdc.inc,package/rel/ti_sdo_edma3_drv.tar.dep)


release release,ti_sdo_edma3_drv: all ti_sdo_edma3_drv.tar
clean:: .clean
	-$(RM) ti_sdo_edma3_drv.tar
	-$(RM) package/rel/ti_sdo_edma3_drv.xdc.inc
	-$(RM) package/rel/ti_sdo_edma3_drv.tar.dep

clean:: .clean
	-$(RM) .libraries $(wildcard .libraries,*)
clean:: 
	-$(RM) .dlls $(wildcard .dlls,*)
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard lib))
    $(shell $(MKDIR) lib)
endif
ifeq (,$(wildcard lib/64p))
    $(shell $(MKDIR) lib/64p)
endif
ifeq (,$(wildcard lib/64p/debug))
    $(shell $(MKDIR) lib/64p/debug)
endif
ifeq (,$(wildcard lib/64p/release))
    $(shell $(MKDIR) lib/64p/release)
endif
ifeq (,$(wildcard lib/674))
    $(shell $(MKDIR) lib/674)
endif
ifeq (,$(wildcard lib/674/debug))
    $(shell $(MKDIR) lib/674/debug)
endif
ifeq (,$(wildcard lib/674/release))
    $(shell $(MKDIR) lib/674/release)
endif
ifeq (,$(wildcard lib/66))
    $(shell $(MKDIR) lib/66)
endif
ifeq (,$(wildcard lib/66/debug))
    $(shell $(MKDIR) lib/66/debug)
endif
ifeq (,$(wildcard lib/66/release))
    $(shell $(MKDIR) lib/66/release)
endif
ifeq (,$(wildcard lib/arm9))
    $(shell $(MKDIR) lib/arm9)
endif
ifeq (,$(wildcard lib/arm9/debug))
    $(shell $(MKDIR) lib/arm9/debug)
endif
ifeq (,$(wildcard lib/arm9/release))
    $(shell $(MKDIR) lib/arm9/release)
endif
ifeq (,$(wildcard lib/a8))
    $(shell $(MKDIR) lib/a8)
endif
ifeq (,$(wildcard lib/a8/debug))
    $(shell $(MKDIR) lib/a8/debug)
endif
ifeq (,$(wildcard lib/a8/release))
    $(shell $(MKDIR) lib/a8/release)
endif
ifeq (,$(wildcard lib/m3))
    $(shell $(MKDIR) lib/m3)
endif
ifeq (,$(wildcard lib/m3/debug))
    $(shell $(MKDIR) lib/m3/debug)
endif
ifeq (,$(wildcard lib/m3/release))
    $(shell $(MKDIR) lib/m3/release)
endif
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
ifeq (,$(wildcard package/lib/lib))
    $(shell $(MKDIR) package/lib/lib)
endif
ifeq (,$(wildcard package/lib/lib/64p))
    $(shell $(MKDIR) package/lib/lib/64p)
endif
ifeq (,$(wildcard package/lib/lib/64p/debug))
    $(shell $(MKDIR) package/lib/lib/64p/debug)
endif
ifeq (,$(wildcard package/lib/lib/64p/debug/ti.sdo.edma3.drv))
    $(shell $(MKDIR) package/lib/lib/64p/debug/ti.sdo.edma3.drv)
endif
ifeq (,$(wildcard package/lib/lib/64p/debug/ti.sdo.edma3.drv/package))
    $(shell $(MKDIR) package/lib/lib/64p/debug/ti.sdo.edma3.drv/package)
endif
ifeq (,$(wildcard package/lib/lib/64p/debug/ti.sdo.edma3.drv/src))
    $(shell $(MKDIR) package/lib/lib/64p/debug/ti.sdo.edma3.drv/src)
endif
ifeq (,$(wildcard package/lib/lib/64p/release))
    $(shell $(MKDIR) package/lib/lib/64p/release)
endif
ifeq (,$(wildcard package/lib/lib/64p/release/ti.sdo.edma3.drv))
    $(shell $(MKDIR) package/lib/lib/64p/release/ti.sdo.edma3.drv)
endif
ifeq (,$(wildcard package/lib/lib/64p/release/ti.sdo.edma3.drv/package))
    $(shell $(MKDIR) package/lib/lib/64p/release/ti.sdo.edma3.drv/package)
endif
ifeq (,$(wildcard package/lib/lib/64p/release/ti.sdo.edma3.drv/src))
    $(shell $(MKDIR) package/lib/lib/64p/release/ti.sdo.edma3.drv/src)
endif
ifeq (,$(wildcard package/lib/lib/674))
    $(shell $(MKDIR) package/lib/lib/674)
endif
ifeq (,$(wildcard package/lib/lib/674/debug))
    $(shell $(MKDIR) package/lib/lib/674/debug)
endif
ifeq (,$(wildcard package/lib/lib/674/debug/ti.sdo.edma3.drv))
    $(shell $(MKDIR) package/lib/lib/674/debug/ti.sdo.edma3.drv)
endif
ifeq (,$(wildcard package/lib/lib/674/debug/ti.sdo.edma3.drv/package))
    $(shell $(MKDIR) package/lib/lib/674/debug/ti.sdo.edma3.drv/package)
endif
ifeq (,$(wildcard package/lib/lib/674/debug/ti.sdo.edma3.drv/src))
    $(shell $(MKDIR) package/lib/lib/674/debug/ti.sdo.edma3.drv/src)
endif
ifeq (,$(wildcard package/lib/lib/674/release))
    $(shell $(MKDIR) package/lib/lib/674/release)
endif
ifeq (,$(wildcard package/lib/lib/674/release/ti.sdo.edma3.drv))
    $(shell $(MKDIR) package/lib/lib/674/release/ti.sdo.edma3.drv)
endif
ifeq (,$(wildcard package/lib/lib/674/release/ti.sdo.edma3.drv/package))
    $(shell $(MKDIR) package/lib/lib/674/release/ti.sdo.edma3.drv/package)
endif
ifeq (,$(wildcard package/lib/lib/674/release/ti.sdo.edma3.drv/src))
    $(shell $(MKDIR) package/lib/lib/674/release/ti.sdo.edma3.drv/src)
endif
ifeq (,$(wildcard package/lib/lib/66))
    $(shell $(MKDIR) package/lib/lib/66)
endif
ifeq (,$(wildcard package/lib/lib/66/debug))
    $(shell $(MKDIR) package/lib/lib/66/debug)
endif
ifeq (,$(wildcard package/lib/lib/66/debug/ti.sdo.edma3.drv))
    $(shell $(MKDIR) package/lib/lib/66/debug/ti.sdo.edma3.drv)
endif
ifeq (,$(wildcard package/lib/lib/66/debug/ti.sdo.edma3.drv/package))
    $(shell $(MKDIR) package/lib/lib/66/debug/ti.sdo.edma3.drv/package)
endif
ifeq (,$(wildcard package/lib/lib/66/debug/ti.sdo.edma3.drv/src))
    $(shell $(MKDIR) package/lib/lib/66/debug/ti.sdo.edma3.drv/src)
endif
ifeq (,$(wildcard package/lib/lib/66/release))
    $(shell $(MKDIR) package/lib/lib/66/release)
endif
ifeq (,$(wildcard package/lib/lib/66/release/ti.sdo.edma3.drv))
    $(shell $(MKDIR) package/lib/lib/66/release/ti.sdo.edma3.drv)
endif
ifeq (,$(wildcard package/lib/lib/66/release/ti.sdo.edma3.drv/package))
    $(shell $(MKDIR) package/lib/lib/66/release/ti.sdo.edma3.drv/package)
endif
ifeq (,$(wildcard package/lib/lib/66/release/ti.sdo.edma3.drv/src))
    $(shell $(MKDIR) package/lib/lib/66/release/ti.sdo.edma3.drv/src)
endif
ifeq (,$(wildcard package/lib/lib/arm9))
    $(shell $(MKDIR) package/lib/lib/arm9)
endif
ifeq (,$(wildcard package/lib/lib/arm9/debug))
    $(shell $(MKDIR) package/lib/lib/arm9/debug)
endif
ifeq (,$(wildcard package/lib/lib/arm9/debug/ti.sdo.edma3.drv))
    $(shell $(MKDIR) package/lib/lib/arm9/debug/ti.sdo.edma3.drv)
endif
ifeq (,$(wildcard package/lib/lib/arm9/debug/ti.sdo.edma3.drv/package))
    $(shell $(MKDIR) package/lib/lib/arm9/debug/ti.sdo.edma3.drv/package)
endif
ifeq (,$(wildcard package/lib/lib/arm9/debug/ti.sdo.edma3.drv/src))
    $(shell $(MKDIR) package/lib/lib/arm9/debug/ti.sdo.edma3.drv/src)
endif
ifeq (,$(wildcard package/lib/lib/arm9/release))
    $(shell $(MKDIR) package/lib/lib/arm9/release)
endif
ifeq (,$(wildcard package/lib/lib/arm9/release/ti.sdo.edma3.drv))
    $(shell $(MKDIR) package/lib/lib/arm9/release/ti.sdo.edma3.drv)
endif
ifeq (,$(wildcard package/lib/lib/arm9/release/ti.sdo.edma3.drv/package))
    $(shell $(MKDIR) package/lib/lib/arm9/release/ti.sdo.edma3.drv/package)
endif
ifeq (,$(wildcard package/lib/lib/arm9/release/ti.sdo.edma3.drv/src))
    $(shell $(MKDIR) package/lib/lib/arm9/release/ti.sdo.edma3.drv/src)
endif
ifeq (,$(wildcard package/lib/lib/a8))
    $(shell $(MKDIR) package/lib/lib/a8)
endif
ifeq (,$(wildcard package/lib/lib/a8/debug))
    $(shell $(MKDIR) package/lib/lib/a8/debug)
endif
ifeq (,$(wildcard package/lib/lib/a8/debug/ti.sdo.edma3.drv))
    $(shell $(MKDIR) package/lib/lib/a8/debug/ti.sdo.edma3.drv)
endif
ifeq (,$(wildcard package/lib/lib/a8/debug/ti.sdo.edma3.drv/package))
    $(shell $(MKDIR) package/lib/lib/a8/debug/ti.sdo.edma3.drv/package)
endif
ifeq (,$(wildcard package/lib/lib/a8/debug/ti.sdo.edma3.drv/src))
    $(shell $(MKDIR) package/lib/lib/a8/debug/ti.sdo.edma3.drv/src)
endif
ifeq (,$(wildcard package/lib/lib/a8/release))
    $(shell $(MKDIR) package/lib/lib/a8/release)
endif
ifeq (,$(wildcard package/lib/lib/a8/release/ti.sdo.edma3.drv))
    $(shell $(MKDIR) package/lib/lib/a8/release/ti.sdo.edma3.drv)
endif
ifeq (,$(wildcard package/lib/lib/a8/release/ti.sdo.edma3.drv/package))
    $(shell $(MKDIR) package/lib/lib/a8/release/ti.sdo.edma3.drv/package)
endif
ifeq (,$(wildcard package/lib/lib/a8/release/ti.sdo.edma3.drv/src))
    $(shell $(MKDIR) package/lib/lib/a8/release/ti.sdo.edma3.drv/src)
endif
ifeq (,$(wildcard package/lib/lib/m3))
    $(shell $(MKDIR) package/lib/lib/m3)
endif
ifeq (,$(wildcard package/lib/lib/m3/debug))
    $(shell $(MKDIR) package/lib/lib/m3/debug)
endif
ifeq (,$(wildcard package/lib/lib/m3/debug/ti.sdo.edma3.drv))
    $(shell $(MKDIR) package/lib/lib/m3/debug/ti.sdo.edma3.drv)
endif
ifeq (,$(wildcard package/lib/lib/m3/debug/ti.sdo.edma3.drv/package))
    $(shell $(MKDIR) package/lib/lib/m3/debug/ti.sdo.edma3.drv/package)
endif
ifeq (,$(wildcard package/lib/lib/m3/debug/ti.sdo.edma3.drv/src))
    $(shell $(MKDIR) package/lib/lib/m3/debug/ti.sdo.edma3.drv/src)
endif
ifeq (,$(wildcard package/lib/lib/m3/release))
    $(shell $(MKDIR) package/lib/lib/m3/release)
endif
ifeq (,$(wildcard package/lib/lib/m3/release/ti.sdo.edma3.drv))
    $(shell $(MKDIR) package/lib/lib/m3/release/ti.sdo.edma3.drv)
endif
ifeq (,$(wildcard package/lib/lib/m3/release/ti.sdo.edma3.drv/package))
    $(shell $(MKDIR) package/lib/lib/m3/release/ti.sdo.edma3.drv/package)
endif
ifeq (,$(wildcard package/lib/lib/m3/release/ti.sdo.edma3.drv/src))
    $(shell $(MKDIR) package/lib/lib/m3/release/ti.sdo.edma3.drv/src)
endif
endif
clean::
	-$(RMDIR) package

.libraries: benchmarking_64P
benchmarking_64P:
	 ofd6x.exe -x lib/release/ti.sdo.edma3.drv.a64P > tmp.xml
	 sectti.exe tmp.xml > lib/release/ti.sdo.edma3.drv.a64P_size.txt
	 $(RM) tmp.xml

clean::
	$(RM) lib/release/ti.sdo.edma3.drv.a64P_size.txt

.libraries: benchmarking_64Pe
benchmarking_64Pe:
	 ofd6x.exe -x lib/release/ti.sdo.edma3.drv.a64Pe > tmp.xml
	 sectti.exe tmp.xml > lib/release/ti.sdo.edma3.drv.a64Pe_size.txt
	 $(RM) tmp.xml

clean::
	$(RM) lib/release/ti.sdo.edma3.drv.a64Pe_size.txt

.libraries: benchmarking_674
benchmarking_674:
	 ofd6x.exe -x lib/release/ti.sdo.edma3.drv.a674 > tmp.xml
	 sectti.exe tmp.xml > lib/release/ti.sdo.edma3.drv.a674_size.txt
	 $(RM) tmp.xml

clean::
	$(RM) lib/release/ti.sdo.edma3.drv.a674_size.txt

.libraries: benchmarking_e64P
benchmarking_e64P:
	 ofd6x.exe -x lib/release/ti.sdo.edma3.drv.ae64P > tmp.xml
	 sectti.exe tmp.xml > lib/release/ti.sdo.edma3.drv.ae64P_size.txt
	 $(RM) tmp.xml

clean::
	$(RM) lib/release/ti.sdo.edma3.drv.ae64P_size.txt

.libraries: benchmarking_e64Pe
benchmarking_e64Pe:
	 ofd6x.exe -x lib/release/ti.sdo.edma3.drv.ae64Pe > tmp.xml
	 sectti.exe tmp.xml > lib/release/ti.sdo.edma3.drv.ae64Pe_size.txt
	 $(RM) tmp.xml

clean::
	$(RM) lib/release/ti.sdo.edma3.drv.ae64Pe_size.txt

.libraries: benchmarking_e674
benchmarking_e674:
	 ofd6x.exe -x lib/release/ti.sdo.edma3.drv.ae674 > tmp.xml
	 sectti.exe tmp.xml > lib/release/ti.sdo.edma3.drv.ae674_size.txt
	 $(RM) tmp.xml

clean::
	$(RM) lib/release/ti.sdo.edma3.drv.ae674_size.txt

.libraries: benchmarking_e66
benchmarking_e66:
	 ofd6x.exe -x lib/release/ti.sdo.edma3.drv.ae66 > tmp.xml
	 sectti.exe tmp.xml > lib/release/ti.sdo.edma3.drv.ae66_size.txt
	 $(RM) tmp.xml

clean::
	$(RM) lib/release/ti.sdo.edma3.drv.ae66_size.txt

.libraries: benchmarking_e66e
benchmarking_e66e:
	 ofd6x.exe -x lib/release/ti.sdo.edma3.drv.ae66e > tmp.xml
	 sectti.exe tmp.xml > lib/release/ti.sdo.edma3.drv.ae66e_size.txt
	 $(RM) tmp.xml

clean::
	$(RM) lib/release/ti.sdo.edma3.drv.ae66e_size.txt

.libraries: benchmarking_e9
benchmarking_e9:
	 ofd6x.exe -x lib/release/ti.sdo.edma3.drv.ae9 > tmp.xml
	 sectti.exe tmp.xml > lib/release/ti.sdo.edma3.drv.ae9_size.txt
	 $(RM) tmp.xml

clean::
	$(RM) lib/release/ti.sdo.edma3.drv.ae9_size.txt

.libraries: benchmarking_ea8f
benchmarking_ea8f:
	 ofd6x.exe -x lib/release/ti.sdo.edma3.drv.aea8f > tmp.xml
	 sectti.exe tmp.xml > lib/release/ti.sdo.edma3.drv.aea8f_size.txt
	 $(RM) tmp.xml

clean::
	$(RM) lib/release/ti.sdo.edma3.drv.aea8f_size.txt

.libraries: benchmarking_em3
benchmarking_em3:
	 ofd6x.exe -x lib/release/ti.sdo.edma3.drv.aem3 > tmp.xml
	 sectti.exe tmp.xml > lib/release/ti.sdo.edma3.drv.aem3_size.txt
	 $(RM) tmp.xml

clean::
	$(RM) lib/release/ti.sdo.edma3.drv.aem3_size.txt


