/*
 *  Copyright 2016 by Texas Instruments Incorporated.
 *
 */

/* this file was generated by xdc/bld/stddefs.xdt */
/*
 *  @(#) gnu.targets; 1, 0, 1,0; 8-18-2016 15:55:44; /db/ztree/library/trees/xdctargets/xdctargets-l06/src/ xlibrary

 */

