#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

include Makedocs.mk
unexport MAKEFILE_LIST
override PKGDIR = ti/mas/swtools
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/Manifest.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/Manifest.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/services/io/package.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/services/io/package.xs
C:/builds/IMGLIB/TI_PRODUCT_3_1_1_0/imglib/ti/mas/swtools/Version2.h.xdt:
package.mak: C:/builds/IMGLIB/TI_PRODUCT_3_1_1_0/imglib/ti/mas/swtools/Version2.h.xdt
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/_gen.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/_gen.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/template.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/template.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/om2.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/om2.xs
C:/builds/IMGLIB/TI_PRODUCT_3_1_1_0/imglib/ti/mas/swtools/Version2.xdt:
package.mak: C:/builds/IMGLIB/TI_PRODUCT_3_1_1_0/imglib/ti/mas/swtools/Version2.xdt
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/xmlgen2.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/xmlgen2.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/ti/targets/elf/TMS470.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/ti/targets/elf/TMS470.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/services/global/Clock.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/services/global/Clock.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/xmlgen.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/xmlgen.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/ti/targets/ITarget.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/ti/targets/ITarget.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/ti/targets/elf/package.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/ti/targets/elf/package.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/ti/targets/elf/ITarget.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/ti/targets/elf/ITarget.xs
package.mak: package.bld
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/ti/targets/package.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/ti/targets/package.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/include/utils.tci:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/include/utils.tci
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/Utils.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/Utils.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/xdc.tci:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/xdc.tci
C:/builds/IMGLIB/TI_PRODUCT_3_1_1_0/imglib/ti/mas/swtools/Copy.xs:
package.mak: C:/builds/IMGLIB/TI_PRODUCT_3_1_1_0/imglib/ti/mas/swtools/Copy.xs
package.mak: docs/doxygen/doxyfile.xdt
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/PackageContents.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/PackageContents.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/Executable.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/Executable.xs
C:/builds/IMGLIB/TI_PRODUCT_3_1_1_0/imglib/ti/mas/swtools/CommonBld.xs:
package.mak: C:/builds/IMGLIB/TI_PRODUCT_3_1_1_0/imglib/ti/mas/swtools/CommonBld.xs
package.mak: config.bld
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/Library.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/Library.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/ITarget.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/ITarget.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/services/global/Trace.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/services/global/Trace.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/package.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/package.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/Script.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/Script.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/BuildEnvironment.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/BuildEnvironment.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/services/io/File.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/services/io/File.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/Repository.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/Repository.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/bld.js:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/bld.js
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/IPackage.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/IPackage.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/package.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/package.xs
C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/ITargetFilter.xs:
package.mak: C:/tools/gen/xdc/xdctools_3_20_05_76/packages/xdc/bld/ITargetFilter.xs
endif

all,54 .libraries,54 .dlls,54 .executables,54 test,54:;
all,54f .libraries,54f .dlls,54f .executables,54f test,54f:;
all,55 .libraries,55 .dlls,55 .executables,55 test,55:;
all,55L .libraries,55L .dlls,55L .executables,55L test,55L:;
all,674 .libraries,674 .dlls,674 .executables,674 test,674:;
all,674e .libraries,674e .dlls,674e .executables,674e test,674e:;
all,e674 .libraries,e674 .dlls,e674 .executables,e674 test,e674:;
all,e674e .libraries,e674e .dlls,e674e .executables,e674e test,e674e:;
all,66 .libraries,66 .dlls,66 .executables,66 test,66:;
all,e66 .libraries,e66 .dlls,e66 .executables,e66 test,e66:;
all,66e .libraries,66e .dlls,66e .executables,66e test,66e:;
all,e66e .libraries,e66e .dlls,e66e .executables,e66e test,e66e:;
all,64 .libraries,64 .dlls,64 .executables,64 test,64:;
all,64e .libraries,64e .dlls,64e .executables,64e test,64e:;
all,64P .libraries,64P .dlls,64P .executables,64P test,64P:;
all,64Pe .libraries,64Pe .dlls,64Pe .executables,64Pe test,64Pe:;
all,e64P .libraries,e64P .dlls,e64P .executables,e64P test,e64P:;
all,e64Pe .libraries,e64Pe .dlls,e64Pe .executables,e64Pe test,e64Pe:;

all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_ti.mas.swtools.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package ti.mas.swtools" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

ifneq (clean,$(MAKECMDGOALS))
-include package/package.cfg.dep
endif

package/package.ext.xml: package/package.cfg.xdc.inc
package/package.cfg.xdc.inc: $(XDCROOT)/packages/xdc/cfg/cfginc.js package.xdc
	@$(MSG) generating schema include file list ...
	$(CONFIG) -f $(XDCROOT)/packages/xdc/cfg/cfginc.js ti.mas.swtools $@

test:;
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,ti_mas_swtools_src_4_6_0_14_beta
ti_mas_swtools_src_4_6_0_14_beta.zip: package/package.rel.dot
ti_mas_swtools_src_4_6_0_14_beta.zip: docs//doxygen//doxyfile.xdt
ti_mas_swtools_src_4_6_0_14_beta.zip: config.bld
ti_mas_swtools_src_4_6_0_14_beta.zip: xdcpaths.mk
ti_mas_swtools_src_4_6_0_14_beta.zip: IpccGen.js
ti_mas_swtools_src_4_6_0_14_beta.zip: package/package.xdc.inc
ti_mas_swtools_src_4_6_0_14_beta.zip: ./swtools_4_6_0_14_beta_release_notes.html
ti_mas_swtools_src_4_6_0_14_beta.zip: dcspecGen.js
ti_mas_swtools_src_4_6_0_14_beta.zip: Makedocs.mk
ti_mas_swtools_src_4_6_0_14_beta.zip: xdcrules.mk
ti_mas_swtools_src_4_6_0_14_beta.zip: Version2.xdt
ti_mas_swtools_src_4_6_0_14_beta.zip: docs//doxygen//Doxyfile
ti_mas_swtools_src_4_6_0_14_beta.zip: makefile
ti_mas_swtools_src_4_6_0_14_beta.zip: CommonBld.xdc
ti_mas_swtools_src_4_6_0_14_beta.zip: mcspecGen.js
ti_mas_swtools_src_4_6_0_14_beta.zip: pccGen.js
ti_mas_swtools_src_4_6_0_14_beta.zip: IVersion2.xs
ti_mas_swtools_src_4_6_0_14_beta.zip: Version.xdt
ti_mas_swtools_src_4_6_0_14_beta.zip: .//docs//doxygen//html//../SWTOOLS.chm
ti_mas_swtools_src_4_6_0_14_beta.zip: package.bld
ti_mas_swtools_src_4_6_0_14_beta.zip: icspecGen.js
ti_mas_swtools_src_4_6_0_14_beta.zip: Ccase.xdc
ti_mas_swtools_src_4_6_0_14_beta.zip: Version.h.xdt
ti_mas_swtools_src_4_6_0_14_beta.zip: mklabelcomp.js
ti_mas_swtools_src_4_6_0_14_beta.zip: CommonBld.xs
ti_mas_swtools_src_4_6_0_14_beta.zip: src
ti_mas_swtools_src_4_6_0_14_beta.zip: Version2.h.xdt
ti_mas_swtools_src_4_6_0_14_beta.zip: Ccase.js
ti_mas_swtools_src_4_6_0_14_beta.zip: package/package.cfg.xdc.inc
ti_mas_swtools_src_4_6_0_14_beta.zip: redirect.js
ti_mas_swtools_src_4_6_0_14_beta.zip: setconfig.js
ti_mas_swtools_src_4_6_0_14_beta.zip: release.js
ti_mas_swtools_src_4_6_0_14_beta.zip: cpytools.pl
ti_mas_swtools_src_4_6_0_14_beta.zip: docs/relnotes_archive
ti_mas_swtools_src_4_6_0_14_beta.zip: package/package.bld.xml
ti_mas_swtools_src_4_6_0_14_beta.zip: IVersion2.xdc
ti_mas_swtools_src_4_6_0_14_beta.zip: IVersion.xdc
ti_mas_swtools_src_4_6_0_14_beta.zip: iCcase.js
ti_mas_swtools_src_4_6_0_14_beta.zip: docs//doxygen//doxygen.h
ti_mas_swtools_src_4_6_0_14_beta.zip: cygwinxdc.bat
ti_mas_swtools_src_4_6_0_14_beta.zip: package/build.cfg
ti_mas_swtools_src_4_6_0_14_beta.zip: ./Version.h
ti_mas_swtools_src_4_6_0_14_beta.zip: package/package.ext.xml
ifneq (clean,$(MAKECMDGOALS))
-include package/rel/ti_mas_swtools_src_4_6_0_14_beta.zip.dep
endif
package/rel/ti_mas_swtools_src_4_6_0_14_beta/ti/mas/swtools/package/package.rel.xml:

ti_mas_swtools_src_4_6_0_14_beta.zip: package/rel/ti_mas_swtools_src_4_6_0_14_beta.xdc.inc package/rel/ti_mas_swtools_src_4_6_0_14_beta/ti/mas/swtools/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELZIP,package/rel/ti_mas_swtools_src_4_6_0_14_beta.xdc.inc,package/rel/ti_mas_swtools_src_4_6_0_14_beta.zip.dep)


release release,ti_mas_swtools_src_4_6_0_14_beta: all ti_mas_swtools_src_4_6_0_14_beta.zip
clean:: .clean
	-$(RM) ti_mas_swtools_src_4_6_0_14_beta.zip
	-$(RM) package/rel/ti_mas_swtools_src_4_6_0_14_beta.xdc.inc
	-$(RM) package/rel/ti_mas_swtools_src_4_6_0_14_beta.zip.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#
	-$(RM) Version.xdc
	-$(RM) Version.h

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package

clean::
	-$(RM)  *.zip
clean::
	-$(RM)  *.bin
clean::
	-$(RM)  *.exe
clean::
	-$(RM)  .//docs//doxygen//*.chm
clean::
	-$(RM)  .//docs/*.chm
clean::
	-$(RMDIR) .//docs//doxygen//html
clean::
	-$(RMDIR) cov_out
clean::
	-$(RMDIR) c54
clean::
	-$(RMDIR) c54f
clean::
	-$(RMDIR) c55
clean::
	-$(RMDIR) c55l
clean::
	-$(RMDIR) c64
clean::
	-$(RMDIR) c64e
clean::
	-$(RMDIR) c674
clean::
	-$(RMDIR) c674e
clean::
	-$(RMDIR) ce66
clean::
	-$(RMDIR) ce66e
clean::
	-$(RMDIR) c64P
clean::
	-$(RMDIR) c64Pe
clean::
	-$(RMDIR) mvarm9
clean::
	-$(RMDIR) gcarmv6
clean::
	-$(RMDIR) gcarmv7a
clean::
	-$(RMDIR) wince
clean::
	-$(RMDIR) tiarmv6le
clean::
	-$(RMDIR) tiarmv6be

